// GENERATED by scripts/build-paul-seed.mjs from paul-data/paul-large-datafiles/
// Do not edit by hand. Regenerate with: node scripts/build-paul-seed.mjs

import type { PaulAuditRow } from "./types";

export const auditFindings: PaulAuditRow[] = [
 {
  "issueId": "crux-false-merge",
  "severity": "high",
  "subject": "Crux Climate",
  "confusedWith": "Crux Alliance",
  "finding": "The original reducer aliased “crux alliance” and “crux” to Crux Climate, then scored Crux Climate 77 for hosting 7 official events.",
  "evidence": "All 7 official host rows are “Crux Alliance” with registration URLs on cruxalliance.org. Zero official host/title rows name Crux Climate or crux.com.",
  "correction": "Keep Crux Climate Inc. (crux.com, NYC/DC climate-fintech) and Crux Alliance (philanthropic/policy network) as separate entities. Remove the 7 hosted events from Crux Climate.",
  "scoreImpact": "Crux Climate engagement points drop to 0; Crux Alliance is not a climate-software prospect."
 },
 {
  "issueId": "scale-ai-phrase",
  "severity": "high",
  "subject": "Scale AI",
  "confusedWith": "English phrase “scale AI” / “at scale”",
  "finding": "Lane C flagged two description-mining hits as lowercase “scale AI” / “scaling… AI”, with no Scale AI org on speaker/host/sponsor lists.",
  "evidence": "Official host/title inventory has many “at Scale” events (utility-scale storage, landscape-scale, AI at Scale) and zero Scale AI hosts.",
  "correction": "Treat Scale AI Climate Week involvement as none. Do not score phrase matches.",
  "scoreImpact": "Engagement 0; remain weak-fit, not a climate-software prospect."
 },
 {
  "issueId": "google-generic-strings",
  "severity": "high",
  "subject": "Google / Alphabet",
  "confusedWith": "Google Forms, Google Books, Android, protest venue",
  "finding": "Prior ranking scored Google 58 from 5 event-text mentions.",
  "evidence": "Lane C inspected those mentions as app-store, form, books, and a protest outside Google Chelsea offices. Official host/title inventory has zero Google hosts.",
  "correction": "Do not treat navigation/vendor strings or adversarial protest as participation. Split Microsoft out of the combined Google profile.",
  "scoreImpact": "Google engagement 0. Microsoft kept separate with unverified description-only notes."
 },
 {
  "issueId": "watershed-scale-nature",
  "severity": "medium",
  "subject": "Watershed (Watershed Technology, Inc.)",
  "confusedWith": "hydrological “watershed-scale”",
  "finding": "Official title match is “Financing and Insuring Watershed-Scale Natural…” hosted by Ducks Unlimited and Munich Re.",
  "evidence": "No official host fragment equals Watershed the company.",
  "correction": "Do not attach that event to Watershed Technology. Prior “4 event texts” remain unverified without descriptions.",
  "scoreImpact": "Engagement scored 0 in this revision (unknown, not invented)."
 },
 {
  "issueId": "climate-x-fashion",
  "severity": "medium",
  "subject": "Climate X",
  "confusedWith": "phrase “climate x fashion leaders”",
  "finding": "Lane B already documented the only artifact match as a student-event phrase, not the company.",
  "evidence": "Zero official host/title rows for Climate X / climate-x.com.",
  "correction": "No Climate Week relationship.",
  "scoreImpact": "Engagement 0."
 },
 {
  "issueId": "jupiter-power-vs-intelligence",
  "severity": "medium",
  "subject": "Jupiter Intelligence",
  "confusedWith": "Jupiter Power",
  "finding": "A fourth “jupiter” title is a fireside with Andy Bowman of Jupiter Power, hosted by Modo Energy.",
  "evidence": "Jupiter Intelligence hosts 3 official events with Impax, SAP, and Arcadis. Jupiter Power is a different energy company.",
  "correction": "Do not merge Jupiter Power into Jupiter Intelligence.",
  "scoreImpact": "Jupiter Intelligence keeps 3 hosted events only."
 },
 {
  "issueId": "sp-followers-not-headcount",
  "severity": "medium",
  "subject": "S&P Global Sustainable1",
  "confusedWith": "LinkedIn follower count as employees",
  "finding": "Prior profile stored 45,691 LinkedIn followers as headcount.",
  "evidence": "Followers are not employees. Parent S&P Global has >40,000 employees; division headcount is unknown.",
  "correction": "headcount_status=unknown for the division; do not reuse 45,691.",
  "scoreImpact": "No score component used headcount; reporting corrected."
 },
 {
  "issueId": "voltera-not-climate-software",
  "severity": "medium",
  "subject": "Voltera",
  "confusedWith": "climate-software company type",
  "finding": "Prior ranking typed Voltera as company-climate-software and ranked it #1 at 82.",
  "evidence": "Lane C describes EV charging/fleet energy infrastructure (EQT-backed), not a climate SaaS product.",
  "correction": "entity_type=company-energy-infrastructure; ICP remains buyer.",
  "scoreImpact": "Climate-software relevance reduced; still a high-engagement buyer."
 },
 {
  "issueId": "ul-not-climate-software",
  "severity": "medium",
  "subject": "UL Solutions",
  "confusedWith": "climate-software company type",
  "finding": "Prior ranking typed UL Solutions as company-climate-software at 78.",
  "evidence": "TIC firm with ULTRUS sustainability software; Silver Partner. Guidehouse roundtables are a different host.",
  "correction": "entity_type=company-tic; partner, not a climate-SaaS peer.",
  "scoreImpact": "Relevance reduced vs prior 78."
 },
 {
  "issueId": "google-microsoft-combined-profile",
  "severity": "medium",
  "subject": "Google",
  "confusedWith": "Microsoft",
  "finding": "Lane C packed Alphabet and Microsoft into one JSON object.",
  "evidence": "Separate public companies with separate Climate Week evidence quality.",
  "correction": "Two records. Microsoft engagement stays unverified in host/title.",
  "scoreImpact": "Independent scores; neither inherits the other’s mentions."
 },
 {
  "issueId": "carbon-mapper-is-host",
  "severity": "low",
  "subject": "Carbon Mapper",
  "confusedWith": "description-only participant",
  "finding": "Lane B called Carbon Mapper a description mention, not a host.",
  "evidence": "Official host field is exactly “Carbon Mapper” for “From Finding to Fixing: Accelerating Action on Methane Super-Emitters”.",
  "correction": "Relation type official_host, high confidence.",
  "scoreImpact": "Engagement counted as hosted event."
 },
 {
  "issueId": "ember-media-partner-discrepancy",
  "severity": "low",
  "subject": "Ember",
  "confusedWith": "Media Partner sponsor",
  "finding": "Coordinator brief called Ember a Media Partner; lane B found Media Partner names were JCDecaux et al., not Ember.",
  "evidence": "No Ember official host row. Speaker-org retained at medium confidence from prior speakers artifact.",
  "correction": "Do not award sponsor points.",
  "scoreImpact": "Speaker-only engagement."
 }
];
