// GENERATED by scripts/build-paul-seed.mjs from paul-data/paul-large-datafiles/
// Do not edit by hand. Regenerate with: node scripts/build-paul-seed.mjs

import type { PaulCandidateRow } from "./types";

export const candidates: PaulCandidateRow[] = [
 {
  "name": "Climate Group",
  "status": "official_host_name",
  "officialHostEvents": 33,
  "notes": "Appears as official host fragment on 33 event(s); not automatically a prospect."
 },
 {
  "name": "Holland Bikes",
  "status": "official_host_name",
  "officialHostEvents": 10,
  "notes": "Appears as official host fragment on 10 event(s); not automatically a prospect."
 },
 {
  "name": "Queens Public Library",
  "status": "official_host_name",
  "officialHostEvents": 24,
  "notes": "Appears as official host fragment on 24 event(s); not automatically a prospect."
 },
 {
  "name": "Solutions House",
  "status": "official_host_name",
  "officialHostEvents": 23,
  "notes": "Appears as official host fragment on 23 event(s); not automatically a prospect."
 },
 {
  "name": "Food Tank",
  "status": "official_host_name",
  "officialHostEvents": 13,
  "notes": "Appears as official host fragment on 13 event(s); not automatically a prospect."
 },
 {
  "name": "Waterfront Alliance",
  "status": "official_host_name",
  "officialHostEvents": 12,
  "notes": "Appears as official host fragment on 12 event(s); not automatically a prospect."
 },
 {
  "name": "XPRIZE Foundation",
  "status": "official_host_name",
  "officialHostEvents": 7,
  "notes": "Appears as official host fragment on 7 event(s); not automatically a prospect."
 },
 {
  "name": "Crux Alliance",
  "status": "has_corrected_profile",
  "officialHostEvents": 7,
  "notes": "See company-research.csv"
 },
 {
  "name": "Holes in the Wall Collective",
  "status": "official_host_name",
  "officialHostEvents": 10,
  "notes": "Appears as official host fragment on 10 event(s); not automatically a prospect."
 },
 {
  "name": "City Harvest",
  "status": "official_host_name",
  "officialHostEvents": 6,
  "notes": "Appears as official host fragment on 6 event(s); not automatically a prospect."
 },
 {
  "name": "Climate Cafe NYC",
  "status": "official_host_name",
  "officialHostEvents": 9,
  "notes": "Appears as official host fragment on 9 event(s); not automatically a prospect."
 },
 {
  "name": "Flood Sensor Aunty",
  "status": "official_host_name",
  "officialHostEvents": 4,
  "notes": "Appears as official host fragment on 4 event(s); not automatically a prospect."
 },
 {
  "name": "Southern Environmental Law Center",
  "status": "official_host_name",
  "officialHostEvents": 5,
  "notes": "Appears as official host fragment on 5 event(s); not automatically a prospect."
 },
 {
  "name": "Sustaining All Life",
  "status": "official_host_name",
  "officialHostEvents": 15,
  "notes": "Appears as official host fragment on 15 event(s); not automatically a prospect."
 },
 {
  "name": "The International Council on Clean Transportation",
  "status": "official_host_name",
  "officialHostEvents": 3,
  "notes": "Appears as official host fragment on 3 event(s); not automatically a prospect."
 },
 {
  "name": "ACT Group",
  "status": "official_host_name",
  "officialHostEvents": 3,
  "notes": "Appears as official host fragment on 3 event(s); not automatically a prospect."
 },
 {
  "name": "Building Energy Exchange",
  "status": "official_host_name",
  "officialHostEvents": 4,
  "notes": "Appears as official host fragment on 4 event(s); not automatically a prospect."
 },
 {
  "name": "Business Council for Sustainable Energy",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "C2ES",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "CMCC Foundation",
  "status": "official_host_name",
  "officialHostEvents": 4,
  "notes": "Appears as official host fragment on 4 event(s); not automatically a prospect."
 },
 {
  "name": "CleanMax",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "Climate Imaginarium",
  "status": "official_host_name",
  "officialHostEvents": 8,
  "notes": "Appears as official host fragment on 8 event(s); not automatically a prospect."
 },
 {
  "name": "Energy",
  "status": "generic_token_not_an_entity",
  "officialHostEvents": 0,
  "notes": "Too generic to treat as an organization."
 },
 {
  "name": "Fordham University",
  "status": "official_host_name",
  "officialHostEvents": 3,
  "notes": "Appears as official host fragment on 3 event(s); not automatically a prospect."
 },
 {
  "name": "Moms Clean Air Force",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "Parking Reform Network",
  "status": "official_host_name",
  "officialHostEvents": 3,
  "notes": "Appears as official host fragment on 3 event(s); not automatically a prospect."
 },
 {
  "name": "PlanetHAUS",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "Rise & Shine Foundation",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "STX Group",
  "status": "has_corrected_profile",
  "officialHostEvents": 2,
  "notes": "See company-research.csv"
 },
 {
  "name": "Sun Valley Forum",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "United Nations Foundation",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "Whole Foods Market",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "the Planetary Health Alliance",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "1.5°Climate",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "3FWILD",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "AECOM",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "AECOM Advisory",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "AIANY Committee on the Environment (COTE)",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "AICPA",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Accion International",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Accounting for Sustainability (A4S)",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Action for Sustainable Development",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Adapt Equity",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Advanced Energy Group",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "Aga Khan Foundation USA | Waterfront Alliance | Open House New York",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Alaska Wilderness League",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Alliance of Bioversity International & CIAT",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Ambrook",
  "status": "has_corrected_profile",
  "officialHostEvents": 2,
  "notes": "See company-research.csv"
 },
 {
  "name": "American Farmland Trust",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "American Forests",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "American Planning Association NY Metro Chapter's Environment",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "American South Asian Network (ASAN)",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Amy Lee Flower",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Aquatic Foods (SAAF)",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Arbor Day Foundation",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "Artichoke Dance Company",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Article One",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Ashurst Perkins Coie x Avalanche Energy x Idemitsu Americas Holdings Corporation",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Avina Foundation",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Battery Park City Authority",
  "status": "official_host_name",
  "officialHostEvents": 6,
  "notes": "Appears as official host fragment on 6 event(s); not automatically a prospect."
 },
 {
  "name": "Ben Tumin (Skipped History)",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Bezos Earth Fund",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Big Reuse at Queens Public Library (QPL)",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Blackhorn Ventures",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Bracewell LLP",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Brand Singapore led by the Ministry of Trade & Industry of Singapore (MTI)",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Bridge Green Upcycle",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Broadscale Group",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Broadway Climate Summit",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Broadway Green Alliance",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Broadway Mall Association",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Bronx River Alliance",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "Business Iceland",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "C40",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "CEART",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "CGIAR Sustainable Animal",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "CIMA",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "CLASP",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "CRS",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "CUE Art",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "California Governor’s Office of Land Use",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "California Sustainable Winegrowing Alliance & California Wines",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Camille Tagle",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Campus Deep Tech & NY Tech Alliance",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Can Manufacturers Institute",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Canary Media",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Castle Hill YMCA",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Center for Climate Integrity",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Center for Earth Ethics",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Center for Resource Solutions  |  NERA",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Center for Sustainable Urban Development",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Circular Supply Chain Network",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "City Parks Foundation & LymeLnk",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "CleanCapital",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Clim-Eat & Laurie M. Tisch Center for Food",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Climate Central",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Climate Film Festival",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "Climate Futures Studio",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Climate Imaginarium & Climate Psychology Alliance of North America",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Climate Innovation (LCI)",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Climate Network",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Climate Salon",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Climate Town & Drilled Media",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "ClimateHaven's Water Innovation Hub",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Co-Founder",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Columbia Climate School",
  "status": "official_host_name",
  "officialHostEvents": 4,
  "notes": "Appears as official host fragment on 4 event(s); not automatically a prospect."
 },
 {
  "name": "Columbia Climate School & Center on Global Energy Policy",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Community Climate Hub (formerly Zero Waste NYC)",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "ConcreteZero",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Coney Island Creek International Coastal Clean-up Coalition",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Consulate General of Denmark in New York",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "CookUnity",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Copenhagen Capacity",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Cornell Atkinson Center for Sustainability",
  "status": "official_host_name",
  "officialHostEvents": 6,
  "notes": "Appears as official host fragment on 6 event(s); not automatically a prospect."
 },
 {
  "name": "Cornell SC Johnson College of Business",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Cornell University's New York State Water Resources Institute",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Creative Enterprise Leadership",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "DC Environmental Film Festival",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "DEPLOY",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "Dartmouth Climate Collaborative",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "Dartmouth Climate Collaborative & Sustainability Office",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Data & Society",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Datamaran",
  "status": "has_corrected_profile",
  "officialHostEvents": 1,
  "notes": "See company-research.csv"
 },
 {
  "name": "David Canassa Strategy & Advisory",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Department of Environmental Conservation (DEC) at Queens Public Library (QPL)",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "Depaul International",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Diestel Family Ranch",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Director of Youth Leadership &amp",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Dr. Neha Arora",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "ECOncrete",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "ERM",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Earth Finance",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Earthshare",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Eccon Soluções Ambientais",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "EcoAge",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Education",
  "status": "generic_token_not_an_entity",
  "officialHostEvents": 0,
  "notes": "Too generic to treat as an organization."
 },
 {
  "name": "Elena Adasheva",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Empire State Realty Trust",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Energy Economic Development Corporation",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "EnergyHub",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "EnergyTag",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Entertainment Network (SEEN) at Columbia's Climate School",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Environment",
  "status": "generic_token_not_an_entity",
  "officialHostEvents": 0,
  "notes": "Too generic to treat as an organization."
 },
 {
  "name": "Environmental Advocates NY",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Fashion",
  "status": "generic_token_not_an_entity",
  "officialHostEvents": 0,
  "notes": "Too generic to treat as an organization."
 },
 {
  "name": "Fed by Blue",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Fetzer Institute's Environment Collaborative",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Finance for the Future",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Fishbear Studios",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Food",
  "status": "generic_token_not_an_entity",
  "officialHostEvents": 0,
  "notes": "Too generic to treat as an organization."
 },
 {
  "name": "Food Systems Lab (J-WAFS) at MIT",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Football for future",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "Forum Energii",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Frankfurt Kurnit",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Friends of the Earth",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "Funders for Regenerative Agriculture",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Fusion Industry Association & CBRE",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Futerra",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Future Food Institute",
  "status": "official_host_name",
  "officialHostEvents": 5,
  "notes": "Appears as official host fragment on 5 event(s); not automatically a prospect."
 },
 {
  "name": "GBPN",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "GBTA Foundation",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "GRACE Communications Foundation",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Genus",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Global ABC / ICBC",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Global Alliance for the Future of Food",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Global Dairy Platform",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Global Fund for a New Economy",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Global Grids Catalyst",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "Globalizing",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "Goodwin Procter",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "Green Sports Alliance",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "GreenPortfolio",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Greenpeace International",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Greenwashed",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Groundswell",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Growald Climate Fund",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Guardians of Flushing Bay at Queens Public Library (QPL)",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Guidehouse",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "H2Au.co",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "HNTB",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Halter",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Health",
  "status": "generic_token_not_an_entity",
  "officialHostEvents": 0,
  "notes": "Too generic to treat as an organization."
 },
 {
  "name": "Health in Climate",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Helsinki Partners",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Henry Street Settlement",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Hollywood Climate Summit",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Hope Vaada Foundation",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Hudson Technologies",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Human Impacts Institute",
  "status": "official_host_name",
  "officialHostEvents": 12,
  "notes": "Appears as official host fragment on 12 event(s); not automatically a prospect."
 },
 {
  "name": "Hydro-Quebec US",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "ICF",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "ICSI/Resilience4Ports",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Ibirapitanga",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Impact Investing Initiative",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "ImpactARC",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Impax Asset Management",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Indigenous Climate Action",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "Infosphere",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Innovation",
  "status": "generic_token_not_an_entity",
  "officialHostEvents": 0,
  "notes": "Too generic to treat as an organization."
 },
 {
  "name": "Innovation Space",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Innovera (nonprofit fiscally sponsored by Buckminster Fuller Institute)",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Institute for Market Transformation",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Institute for Progress",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Institute for Transportation & Development Policy",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Institutes for Planetary Health",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "International Aluminium Institute",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "International Livestock Research Institute (ILRI)",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "International Network of Energy Transition Think Tanks",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Investment (SI3) Specialization",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Investors Circle & Microfinance",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "JLL",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Juliana Castaneda",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Jupiter Intelligence",
  "status": "has_corrected_profile",
  "officialHostEvents": 3,
  "notes": "See company-research.csv"
 },
 {
  "name": "Jupiter Intelligence &amp",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "K&L Gates",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "LACI at BATWorks",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "LC3",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Light Hill Collaborative",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Lithuania",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "London",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Lonely Whale",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Los Angeles Cleantech Incubator (LACI)",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Lower East Side Employment Network",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Lucas + Carroll",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Lucid Motors",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "L’EAUTELIER",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "MESH_ARTS in collaboration with BioBAT Art Space",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "MIT Alumni Energy",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "MIT Club of NY",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "MIT Sloan Club of NY",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Macdoch Foundation",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Madison Energy Infrastructure",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "McKnight Foundation",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Medical Society Consortium on Climate",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Metropolitan Abundance Project",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "Michelman Robinson",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Milkywire",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Mitsubishi Electric",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Monarch Group",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Morningstar Sustainalytics",
  "status": "has_corrected_profile",
  "officialHostEvents": 1,
  "notes": "See company-research.csv"
 },
 {
  "name": "Morrison Foerster",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Mothers Out Front",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Museum of the Moving Image",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Music Sustainability Alliance",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "NRDC",
  "status": "official_host_name",
  "officialHostEvents": 3,
  "notes": "Appears as official host fragment on 3 event(s); not automatically a prospect."
 },
 {
  "name": "NRDC (Natural Resources Defense Council)",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "NY Climate Exchange",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "NY Hardware Meetup",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "NYC Department of Parks",
  "status": "official_host_name",
  "officialHostEvents": 3,
  "notes": "Appears as official host fragment on 3 event(s); not automatically a prospect."
 },
 {
  "name": "NYU Wagner Social Impact",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "NatH2Investing.com & Stinson LLP",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Natural Resources Defense Council",
  "status": "official_host_name",
  "officialHostEvents": 3,
  "notes": "Appears as official host fragment on 3 event(s); not automatically a prospect."
 },
 {
  "name": "Neste",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "Nevada Clinicians for Climate Action",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "New York Energy Democracy Alliance",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "New York Passive House",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "New York Sea Grant",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "New York University",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "New York University School of Professional Studies Center for Global Affairs",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Nicolaas G. Pierson Foundation",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Novadaur",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "O Mundo Que Queremos",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Ocean Visions",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Open Environmental Data Project",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Open Planet Studios",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Organizing)",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Oslo & Co",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Out for Sustainability (Out4S)",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Oxfam",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Oxford University",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Partners",
  "status": "generic_token_not_an_entity",
  "officialHostEvents": 0,
  "notes": "Too generic to treat as an organization."
 },
 {
  "name": "Partnership for Carbon Accounting Financials (PCAF) & Deutsche Bank",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Pensa",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "PepsiCo",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Planet",
  "status": "generic_token_not_an_entity",
  "officialHostEvents": 0,
  "notes": "Too generic to treat as an organization."
 },
 {
  "name": "Planted Society",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Pledge 1%",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Policy",
  "status": "generic_token_not_an_entity",
  "officialHostEvents": 0,
  "notes": "Too generic to treat as an organization."
 },
 {
  "name": "Pratt Institute",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "Pratt Institute Graduate Communications Design",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Precious Plastic NYC",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Project 17 Nigeria",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Project Everyone",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Protiviti",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Public Affairs",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Quinn+Partners",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "ReNew 2030",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Recreation",
  "status": "generic_token_not_an_entity",
  "officialHostEvents": 0,
  "notes": "Too generic to treat as an organization."
 },
 {
  "name": "Refrigerant Emissions Elimination Forum (REEF)",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Regional Plan Association",
  "status": "official_host_name",
  "officialHostEvents": 3,
  "notes": "Appears as official host fragment on 3 event(s); not automatically a prospect."
 },
 {
  "name": "Reproductive Health",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Resilient Red Hook",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Resource Justice Network",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Retro Report",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "SDG Action Campaign",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "SITELAB urban studio",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "SPECTRA Super Pollutant Elimination Alliance",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Said Business School",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Save the Waves",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "School of International",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Seedlings Collective",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Shift",
  "status": "generic_token_not_an_entity",
  "officialHostEvents": 0,
  "notes": "Too generic to treat as an organization."
 },
 {
  "name": "Shirley Chisholm State Park",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Society for Earth Law",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Solidarity Center",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "South Street Seaport Museum",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "Southeast Sustainability Directors Network (SSDN) + New York University (NYU) Sc",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Sponsored By: American Geophysical Union",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Stacks+Joules",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Stakeholder Forum for a Sustainable Future",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Stanford University Doerr School of Sustainability",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Stockholm Business Region",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Strong Roots",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Support + Feed",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Surfrider Foundation",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "Sustainability",
  "status": "generic_token_not_an_entity",
  "officialHostEvents": 0,
  "notes": "Too generic to treat as an organization."
 },
 {
  "name": "Sustainability Network (EESN)",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Sustainability at Harvard University",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Sustainable Entertainment Alliance",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Sustainable Shipping Initiative",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Sylvera",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Systemiq",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Taiwan Green Energy for Charity Association (TGECA)",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Taylor Geospatial",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "The 5 Gyres Institute",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "The Bee Conservancy at Queens Public Library (QPL)",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "The Circular Value Institute",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "The Climate Chain Reaction - Founder",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "The Climate Guys",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "The Conference Board",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "The Degrees Initiative",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "The Educated Choices Program",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "The Environmental Justice Oral History Project",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "The Frontline Resource Institute at Environmental Defense Fund",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "The Green Launchpad",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "The Independent",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "The International Foundation for the Displaced (IFD)",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "The Living Table",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "The Nature Conservancy",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "The Nest Campus",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "The New York Climate Exchange",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "The Parking Reform Network",
  "status": "official_host_name",
  "officialHostEvents": 4,
  "notes": "Appears as official host fragment on 4 event(s); not automatically a prospect."
 },
 {
  "name": "The Pulitzer Center",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "The Rockefeller Foundation",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "The Salata Institute for Climate",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "The U.S. Conference of Mayors",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "The YEARS Project",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Thirst Foundation",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Tractor Beam & BEAM",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Trillium Asset Management",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "U.S. Green Building Council",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "UNEP",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "UPROSE",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "US Aluminum Association",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "US Sustainable Investment Forum & Food Systems for the Future Institute (kindly",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Union of Concerned Scientists",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "United Nations Department of Global Communications",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "United Nations Development Programme",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "United Nations Environment Programme",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "United Nations Global Compact",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "United Nations Global Compact Network USA",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "United Nations Office for Partnerships",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Urban Future Lab (UFL)",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Urban Indigenous Collective",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "WBCSD",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "WE ACT for Environmental Justice",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "WICE Foundation in partnership with the Central African Forest Commission (COMIF",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "WIEGO (Women in Informal Employment",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "WILDCOAST",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "WXY architecture + urban design",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Wallet Max™",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Walton Family Foundation",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Waterfront Committees",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "WeTheAtlas",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "White & Case",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Why Regenerative",
  "status": "official_host_name",
  "officialHostEvents": 5,
  "notes": "Appears as official host fragment on 5 event(s); not automatically a prospect."
 },
 {
  "name": "Wild Tomorrow",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "Willdan Clean Energy Academy",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Working Horizons",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "World Intellectual Property Organization",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "World Wildlife Foundation",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "World Wildlife Fund (WWF)",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Wythe Futures",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Zacua Ventures",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "featuring SpatiaFi",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "iMasons Climate Accord",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "the Business Council for Sustainable Energy",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "the Carbon Leadership Forum NYC",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "the Global Climate Change-Homelessness Network",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "the Hopkins Population Center",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "the NYC Mayor’s Office",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "the New York Restoration Project",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "the William H. Gates Sr. Institute for Population",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "​The Abdul Latif Jameel Water",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "50 Shades of Green",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "ASC",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "American Clean Power Association",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Apolitical",
  "status": "has_corrected_profile",
  "officialHostEvents": 0,
  "notes": "See company-research.csv"
 },
 {
  "name": "Aquaculture Stewardship Council (ASC)",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Audubon",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "BCG",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Bloomberg New Energy Finance",
  "status": "has_corrected_profile",
  "officialHostEvents": 0,
  "notes": "See company-research.csv"
 },
 {
  "name": "BlueGreen Alliance (BGA)",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Bluegreen Alliance",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Boston Consulting Group",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "CCIP Ltd",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Center for Climate & Security",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Cheerful Twentyfirst",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "China Renewable Energy Industry Association",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Clean Air Fund",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Climate and Clean Air Coalition",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "ClimateWorks Foundation",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "CoreWeave",
  "status": "has_corrected_profile",
  "officialHostEvents": 0,
  "notes": "See company-research.csv"
 },
 {
  "name": "Cornell University",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Daikin",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Daikin U.S. Corporation",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Dialogue Earth",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Earthshot Prize",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Elemental Impact",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Ellen MacArthur Foundation",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Ember",
  "status": "has_corrected_profile",
  "officialHostEvents": 0,
  "notes": "See company-research.csv"
 },
 {
  "name": "Environment and Health (UNU-INWEH)",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Environmental Law Institute",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Fair Trade USA",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Federation of American Scientists",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Fortescue",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Fossil Fuel Treaty",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "French Ministry of Foreign Affairs",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Harvard C-CHANGE",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "HiImpact",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Hydro Quebec-1",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "IEA",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Industrial Deep Decarbonization Initiative (IDDI)",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Italy",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "JCDecaux",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "L'Oréal Groupe",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "LOreal Groupe",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Maryland Department of Environment",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "NYC Tourism and Conventions",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "New York State Office of General Services",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Newsweek",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Newton",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Nike",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "PG&E",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Pernod Ricard",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Pfizer",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Philanthropist",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Polecat",
  "status": "has_corrected_profile",
  "officialHostEvents": 0,
  "notes": "See company-research.csv"
 },
 {
  "name": "Port of Long Beach",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Princeton Digital Group",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Project Syndicate",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "ResponsibleSteel",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Reuters",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Reuters Plus",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Rockwell Automation",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Salesforce",
  "status": "has_corrected_profile",
  "officialHostEvents": 0,
  "notes": "See company-research.csv"
 },
 {
  "name": "Siemens",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Spark Climate Solutions",
  "status": "official_host_name",
  "officialHostEvents": 2,
  "notes": "Appears as official host fragment on 2 event(s); not automatically a prospect."
 },
 {
  "name": "State of California",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Sustainable Energy for All",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Sweden",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "TIME",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "TNFD",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Takeda",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "The Global Methane Hub",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "The Pew Charitable Trusts",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Third Act",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Three Cairns Group",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Tilt Collective",
  "status": "official_host_name",
  "officialHostEvents": 1,
  "notes": "Appears as official host fragment on 1 event(s); not automatically a prospect."
 },
 {
  "name": "Trane Technologies",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Trust for America’s Health",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "U.S. Senate",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "UL Solutions",
  "status": "has_corrected_profile",
  "officialHostEvents": 0,
  "notes": "See company-research.csv"
 },
 {
  "name": "UNOPS",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Unilever",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "United Nations World Food Programme",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Voltera",
  "status": "has_corrected_profile",
  "officialHostEvents": 0,
  "notes": "See company-research.csv"
 },
 {
  "name": "Wellcome Trust",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 },
 {
  "name": "Wood Mackenzie",
  "status": "has_corrected_profile",
  "officialHostEvents": 0,
  "notes": "See company-research.csv"
 },
 {
  "name": "Zero Waste Foundation",
  "status": "unresolved_name",
  "officialHostEvents": 0,
  "notes": "Name only; original typed JSON with roles was not in this packet."
 }
];
