// GENERATED by scripts/build-paul-seed.mjs from paul-data/paul-large-datafiles/
// Do not edit by hand. Regenerate with: node scripts/build-paul-seed.mjs

import type { PaulIntentRow } from "./types";

export const intentMappings: PaulIntentRow[] = [
 {
  "artifactCategory": "Company Research (Corrected)",
  "artifactPath": "paul-company-research-updated/company-research.json",
  "rowClassOrScope": "Entire File (26 scored company profiles)",
  "count": "26",
  "disposition": "RESHAPE",
  "targetUseCase": "Use Case 1 (Reference) & Use Case 2",
  "rationale": "Built under flawed climate software vendor frame. 0/26 fit Seed Midwest CRO ICP. Contains 2 climate-risk data providers (Jupiter Climate X) and key partner intelligence.",
  "astraAction": "Do not present as CRO prospect pipeline. Extract Jupiter and Climate X as niche case studies; reference enterprise names as non-target benchmarks."
 },
 {
  "artifactCategory": "Company Research (Corrected)",
  "artifactPath": "paul-company-research-updated/company-research.json",
  "rowClassOrScope": "Mega-Corps & Hyperscalers (Google Microsoft Salesforce)",
  "count": "3",
  "disposition": "DROP",
  "targetUseCase": "Neither",
  "rationale": "Massive public tech giants (83k to 228k employees). Completely irrelevant as fractional CRO buyers; cannot buy fractional services.",
  "astraAction": "Omit from CRO prospect pipeline; include in appendix only as explicit non-fit examples."
 },
 {
  "artifactCategory": "Company Research (Corrected)",
  "artifactPath": "paul-company-research-updated/company-research.json",
  "rowClassOrScope": "Testing Inspection & Certification (TIC) & Large Infra (UL Solutions Sunrun CoreWeave)",
  "count": "3",
  "disposition": "DROP",
  "targetUseCase": "Neither",
  "rationale": "UL Solutions is 14k+ employee public TIC; Sunrun is 9k employee public solar; CoreWeave is 2.1k public AI infra. Wrong org size and business model.",
  "astraAction": "Drop from CRO pipeline. Cite UL Solutions as proof of prior geographic false-positive (Midwest HQ but 14k employees)."
 },
 {
  "artifactCategory": "Company Research (Corrected)",
  "artifactPath": "paul-company-research-updated/company-research.json",
  "rowClassOrScope": "Private Equity & Large Acquired Platforms (Wood Mackenzie STX Group Morningstar Sustainalytics Kayrros)",
  "count": "4",
  "disposition": "DROP",
  "targetUseCase": "Neither",
  "rationale": "PE-owned or corporate subsidiaries (400 to 2900+ headcount or acquired like Kayrros). Mature sales orgs; not early-stage founder-led.",
  "astraAction": "Exclude from CRO target lists; do not reopen acquisition or PE research."
 },
 {
  "artifactCategory": "Company Research (Corrected)",
  "artifactPath": "paul-company-research-updated/company-research.json",
  "rowClassOrScope": "Nonprofits Think Tanks & Coalitions (Crux Alliance Carbon Mapper Ember Apolitical)",
  "count": "4",
  "disposition": "DROP",
  "targetUseCase": "Neither",
  "rationale": "Nonprofit 501(c)(3) entities and policy networks. They do not have commercial revenue operations or quota-bearing sales motions.",
  "astraAction": "Exclude from CRO pipeline. Keep Crux Alliance vs Crux Climate distinction preserved."
 },
 {
  "artifactCategory": "Company Research (Corrected)",
  "artifactPath": "paul-company-research-updated/company-research.json",
  "rowClassOrScope": "Growth Stage / Series B & C Climate Tech (Watershed Datamaran Crux Climate Ambrook Voltera Octopus/Kraken)",
  "count": "6",
  "disposition": "DROP",
  "targetUseCase": "Neither",
  "rationale": "Well past Seed stage (Series B/C or PE-backed $50M to $239M+ raised). Employ full-time VPs of Sales and large commercial teams.",
  "astraAction": "Drop from active CRO prospecting. Treat as market landscape references only."
 },
 {
  "artifactCategory": "Company Research (Corrected)",
  "artifactPath": "paul-company-research-updated/company-research.json",
  "rowClassOrScope": "Climate-Risk Data Providers Niche (Jupiter Intelligence Climate X)",
  "count": "2",
  "disposition": "RESHAPE",
  "targetUseCase": "Use Case 1 (Niche Carve-Out) & Use Case 2",
  "rationale": "Both match the specific two climate-risk data providers niche mandate. Jupiter is Series C (53 HC CA); Climate X is Series A (89 HC UK).",
  "astraAction": "Present as named niche exceptions. Frame for strategic advisory or specialized commercial acceleration distinct from core Midwest Seed pipeline."
 },
 {
  "artifactCategory": "Company Research (Corrected)",
  "artifactPath": "paul-company-research-updated/company-research.json",
  "rowClassOrScope": "Early-Stage Software & Intelligence (Polecat)",
  "count": "1",
  "disposition": "RESHAPE",
  "targetUseCase": "Use Case 1 (Secondary)",
  "rationale": "24 to 30 headcount fits size band but Series A was 8 years ago and UK-based. Borderline turnaround or niche data intelligence fit.",
  "astraAction": "List as secondary/contingent profile; verify current operating status."
 },
 {
  "artifactCategory": "Company Research (Corrected)",
  "artifactPath": "paul-company-research-updated/candidate-universe-status.csv",
  "rowClassOrScope": "Official Host Names (e.g. Climate Group Queens Public Library museums)",
  "count": "336",
  "disposition": "DROP",
  "targetUseCase": "Neither",
  "rationale": "Official event host fragments mechanically extracted from official 838 calendar. 95%+ are public bodies universities NGOs or cultural institutions.",
  "astraAction": "Do not attempt to enrich or score as CRO prospects; keep as event host metadata only."
 },
 {
  "artifactCategory": "Company Research (Corrected)",
  "artifactPath": "paul-company-research-updated/candidate-universe-status.csv",
  "rowClassOrScope": "Generic Keyword Tokens & Phrase Matches (Scale AI matches climate etc.)",
  "count": "13",
  "disposition": "DROP",
  "targetUseCase": "Neither",
  "rationale": "Linguistic false-positives from regex scanning event titles/descriptions (e.g. at scale Google meet). Not real companies.",
  "astraAction": "Permanently discard; do not include in any presentation or scoreboard."
 },
 {
  "artifactCategory": "Company Research (Corrected)",
  "artifactPath": "paul-company-research-updated/candidate-universe-status.csv",
  "rowClassOrScope": "Unresolved Candidate Names",
  "count": "116",
  "disposition": "DROP",
  "targetUseCase": "Neither",
  "rationale": "Raw unprofiled text strings without funding headcount or geographic data. Better to generate fresh pipeline from VC portfolios.",
  "astraAction": "Do not spend cycles enriching. Replace with warm portfolio lists from Chicago Ventures and GTM Fund."
 },
 {
  "artifactCategory": "Company Research (Corrected)",
  "artifactPath": "paul-company-research-updated/entity-resolution-audit.csv",
  "rowClassOrScope": "Identity Audit Table (Crux Alliance vs Crux Climate Voltera Scale AI Google)",
  "count": "4",
  "disposition": "KEEP",
  "targetUseCase": "Operational Governance",
  "rationale": "Essential documentation preventing regression of resolved identity conflations.",
  "astraAction": "Preserve as audit standard in handoff documentation."
 },
 {
  "artifactCategory": "Company Research (Corrected)",
  "artifactPath": "paul-company-research-updated/company-event-relationships.csv",
  "rowClassOrScope": "Company-to-Event Cross-Reference Table",
  "count": "67",
  "disposition": "RESHAPE",
  "targetUseCase": "Use Case 2 (Climate Week)",
  "rationale": "Shows which companies are hosting or speaking. Useful for Paul's on-the-ground event navigation not for CRO lead scoring.",
  "astraAction": "Repurpose as an event preparation cheat sheet for Paul's meetings."
 },
 {
  "artifactCategory": "Company Research (Corrected)",
  "artifactPath": "paul-company-research-updated/prospect-ranking.csv & prospects-only.csv",
  "rowClassOrScope": "Ranked Prospect Scorecards (0–100 rubric)",
  "count": "26",
  "disposition": "DROP",
  "targetUseCase": "Neither",
  "rationale": "Scores companies on their relevance to buying climate software. Entirely obsolete for fractional CRO client scoring.",
  "astraAction": "Retire this ranking table; replace with the 6-test Fractional CRO ICP scorecard."
 },
 {
  "artifactCategory": "Climate Week Networking",
  "artifactPath": "paul-climate-week-outputs/networking/ranked-top10.csv",
  "rowClassOrScope": "Ranked Top 10 Priority Events",
  "count": "10",
  "disposition": "RESHAPE",
  "targetUseCase": "Use Case 2 (Climate Week)",
  "rationale": "High-signal events (Greentown Labs Showcase Climate Capital Summit Collab Fund Demo Series) but ranked under general networking rubric.",
  "astraAction": "Re-rank around Seed to A founder and investor density; highlight admission status (open vs waitlist vs approval required)."
 },
 {
  "artifactCategory": "Climate Week Networking",
  "artifactPath": "paul-climate-week-outputs/networking/ranked-top20.csv",
  "rowClassOrScope": "Ranked Top 20 Events (Next 10)",
  "count": "10",
  "disposition": "RESHAPE",
  "targetUseCase": "Use Case 2 (Climate Week)",
  "rationale": "Mix of high-value showcases (Newlab Venture for ClimateTech Founder Speed Matching) and low-fit policy panels (UN Global Compact).",
  "astraAction": "Promote founder-matching and showcase events; demote corporate policy panels to secondary."
 },
 {
  "artifactCategory": "Climate Week Networking",
  "artifactPath": "paul-climate-week-outputs/networking/qualified-climate-tech-networking-longlist.csv",
  "rowClassOrScope": "Qualified Networking Longlist (99 events)",
  "count": "99",
  "disposition": "RESHAPE",
  "targetUseCase": "Use Case 2 (Climate Week)",
  "rationale": "95 core week + 4 adjacent events. Verified dates and locations. Strong baseline of climate week activity but needs operator stage tagging.",
  "astraAction": "Apply Seed to A Founder/VC Density tag; group into daily calendar blocks (Sep 20–27)."
 },
 {
  "artifactCategory": "Climate Week Networking",
  "artifactPath": "paul-climate-week-outputs/networking/excluded-from-qualified.csv",
  "rowClassOrScope": "Founder & Operator Networking Events (Excluded as General Tech)",
  "count": "6",
  "disposition": "RESHAPE",
  "targetUseCase": "Use Case 1 & Use Case 2",
  "rationale": "Wrongly excluded for not being climate-only: includes Founders Funders & Fractionals NYC Founders & Operators Breakfast NYC Founders Club.",
  "astraAction": "Reclaim and restore these events into Paul's Climate Week schedule as prime CRO networking opportunities."
 },
 {
  "artifactCategory": "Climate Week Networking",
  "artifactPath": "paul-climate-week-outputs/networking/excluded-from-qualified.csv",
  "rowClassOrScope": "Community / Cultural / Library Workshops",
  "count": "11",
  "disposition": "DROP",
  "targetUseCase": "Neither",
  "rationale": "Upcycling workshops public library digital labs film narrative summits. Correctly excluded.",
  "astraAction": "Confirm permanent exclusion; do not reopen."
 },
 {
  "artifactCategory": "Climate Week Networking",
  "artifactPath": "paul-climate-week-outputs/networking/candidate-pending-verification.csv",
  "rowClassOrScope": "High-Value VC/Founder Candidate Events",
  "count": "~25",
  "disposition": "RESHAPE",
  "targetUseCase": "Use Case 2 (Climate Week)",
  "rationale": "Top-tier founder events left in pending (e.g. Venture Climate Alliance Scaling Playbook Greentown From Lab to Scale Climate Investment When AI Meets Physical World).",
  "astraAction": "Extract and verify admission links for the top 10 VC/founder events in this file."
 },
 {
  "artifactCategory": "Climate Week Networking",
  "artifactPath": "paul-climate-week-outputs/networking/candidate-pending-verification.csv",
  "rowClassOrScope": "Institutional & Academic Pending Events",
  "count": "~89",
  "disposition": "DROP",
  "targetUseCase": "Neither",
  "rationale": "University alumni panels UN side-sessions and municipal forums with low founder/commercial concentration.",
  "astraAction": "Deprioritize; do not spend presentation space on unverified academic/institutional sessions."
 },
 {
  "artifactCategory": "Climate Week Networking",
  "artifactPath": "paul-climate-week-outputs/networking/recommendations-and-itinerary.md",
  "rowClassOrScope": "Existing Daily Itinerary & Recommendations",
  "count": "1",
  "disposition": "RESHAPE",
  "targetUseCase": "Use Case 2 (Climate Week)",
  "rationale": "Good operational structure but schedule incorporates corporate policy events instead of pure founder/VC interactions.",
  "astraAction": "Restructure into an executive stage-filtered Climate Week Master Calendar for Paul."
 },
 {
  "artifactCategory": "Climate Week Networking",
  "artifactPath": "paul-climate-week-outputs/source-inventory/official838.csv",
  "rowClassOrScope": "Official Climate Week Event Inventory (838 events)",
  "count": "838",
  "disposition": "RESHAPE",
  "targetUseCase": "Use Case 2 (Discovery Baseline)",
  "rationale": "Unfiltered raw inventory of all official submissions. 80%+ are corporate marketing NGO panels or closed diplomatic meetings.",
  "astraAction": "Do not dump 838 events. Retain as a searchable lookup index only."
 },
 {
  "artifactCategory": "Provisional Company Research",
  "artifactPath": "paul-climate-week-outputs/company-research-provisional/HISTORICAL-UNCORRECTED-prospect-ranking.md",
  "rowClassOrScope": "Uncorrected Historical Ranking Report",
  "count": "1",
  "disposition": "DROP",
  "targetUseCase": "Neither",
  "rationale": "Contains the confirmed Crux Alliance / Crux Climate conflation and flawed rubric.",
  "astraAction": "Permanently retired; must never be reopened or cited by Astra."
 }
];
