// GENERATED by scripts/build-paul-seed.mjs from paul-data/paul-large-datafiles/
// Do not edit by hand. Regenerate with: node scripts/build-paul-seed.mjs

import type { PaulLaneProfileRow } from "./types";

export const laneProfiles: PaulLaneProfileRow[] = [
 {
  "lane": "A",
  "name": "Watershed (Watershed Technology, Inc.)",
  "category": "Carbon accounting / enterprise sustainability SaaS (climate data & AI)",
  "website": "https://www.watershed.com",
  "hq": "San Francisco, California, USA",
  "founded": "2019",
  "stage": "Private - Series C ($100M, Feb 2024, led by Greenoaks; $1.8B valuation; incl. Kleiner Perkins, Sequoia)",
  "fundingSummary": "~$239M total raised (Silicon Valley Investclub profile; PitchBook lists 18 investors)",
  "headcount": "370 (LinkedIn, +13.2% YoY, Jun 2026); 400 (PitchBook); 550+ (company-affiliated profile)",
  "headcountSource": "LinkedIn company page 2026-06-26; PitchBook profile",
  "products": "Enterprise sustainability platform: carbon measurement/reporting, CSRD/CDP compliance, AI-powered product footprints, climate data APIs",
  "icpFit": "competitor",
  "icpNotes": "Direct competitor for carbon accounting SaaS; potential partner for climate data standards",
  "climateWeekInvolvement": "Mentioned in 4 official Climate Week NYC 2026 event texts (task2-description-mining.json)",
  "sources": [
   {
    "url": "https://watershed.com/blog/series-c"
   },
   {
    "url": "https://pitchbook.com/profiles/company/439873-75"
   },
   {
    "url": "https://linkedin.com/company/watershedclimate"
   },
   {
    "url": "https://www.bloomberg.com/news/articles/2024-02-01/watershed-climate-data-service-secures-100-million-funding-round"
   }
  ]
 },
 {
  "lane": "A",
  "name": "Polecat (Polecat Intelligence Ltd.)",
  "category": "Climate risk intelligence SaaS (risk & reputation analytics)",
  "website": "https://www.polecat.com",
  "hq": "London, UK (Bristol-origin; presence UK/US/NL/ZA/PL)",
  "founded": "2007",
  "stage": "Private - Series A (~$4.1-5.3M total raised; last round ~8 yrs ago)",
  "fundingSummary": "~$4.13M (Tracxn 2026); $5.29M (CB Insights); LinkedIn lists $4.2M",
  "headcount": "24 (LinkedIn 2026, +7.5% YoY); 30 (Latka 2024)",
  "headcountSource": "LinkedIn company page; getlatka.com",
  "products": "Risk intelligence platform: ESG/climate/supply-chain risk monitoring from online data",
  "icpFit": "partner",
  "icpNotes": "Small team; partner for risk data rather than a large-budget buyer",
  "climateWeekInvolvement": "Impact Partner sponsor of Climate Week NYC 2026 (cw-sponsors-partners-raw.json)",
  "sources": [
   {
    "url": "https://linkedin.com/company/polecat"
   },
   {
    "url": "https://www.cbinsights.com/company/polecat-1"
   },
   {
    "url": "https://tracxn.com/d/companies/polecat/"
   },
   {
    "url": "https://www.polecat.com/about"
   }
  ]
 },
 {
  "lane": "A",
  "name": "Datamaran",
  "category": "ESG policy/risk analysis SaaS (AI-driven)",
  "website": "https://www.datamaran.com",
  "hq": "London, UK (presence US, NL, ES)",
  "founded": "2014",
  "stage": "Private - Series C ($32.6M growth financing from Morgan Stanley Expansion Capital, Sep 2024)",
  "fundingSummary": "Series C $33M announced 2024-09-19 (Business Wire); ARR more than doubled since Series B",
  "headcount": "107 (LinkedIn, -17.2% YoY, Jun 2026); 124 (PitchBook); 133 (Latka 2024)",
  "headcountSource": "LinkedIn company page 2026-06-28; PitchBook",
  "products": "AI platform monitoring external ESG risks, regulations, and policy for board-level reporting",
  "icpFit": "competitor",
  "icpNotes": "Adjacent competitor (ESG policy analytics); possible integration partner",
  "climateWeekInvolvement": "Mentioned in 1 official Climate Week NYC 2026 event text",
  "sources": [
   {
    "url": "https://www.businesswire.com/news/home/20240917234304/en/"
   },
   {
    "url": "https://pitchbook.com/profiles/company/136970-11"
   },
   {
    "url": "https://linkedin.com/company/datamaran"
   }
  ]
 },
 {
  "lane": "A",
  "name": "UL Solutions Inc.",
  "category": "Testing/inspection/certification (TIC) + sustainability software (ULTRUS)",
  "website": "https://www.ul.com",
  "hq": "Northbrook, Illinois, USA",
  "founded": "1894",
  "stage": "Public - NYSE: ULS (IPO April 2024); strong FY2025 results, 2026 growth outlook, raised dividend",
  "fundingSummary": "Public company; Q4/FY2025 10-K filed 2026-02-19",
  "headcount": "14,635 (AltIndex via LinkedIn, Aug 2026, +2.8% QoQ); ~8,400 core on LinkedIn page",
  "headcountSource": "AltIndex ULS employee trends 2026-08-15; LinkedIn company page",
  "products": "Safety science, certification, and compliance software incl. sustainability/ESG data services",
  "icpFit": "partner",
  "icpNotes": "Large enterprise; partner for validation/certification and distribution; also a buyer of climate software internally",
  "climateWeekInvolvement": "Silver Partner sponsor of Climate Week NYC 2026; Guidehouse Climate Week Roundtable is a separate event host",
  "sources": [
   {
    "url": "https://altindex.com/ticker/uls/employees-linkedin"
   },
   {
    "url": "https://last10k.com/sec-filings/uls/0001901440-26-000005.htm"
   },
   {
    "url": "https://www.roic.ai/quote/ULS/transcripts/2026-year/2-quarter"
   }
  ]
 },
 {
  "lane": "A",
  "name": "Salesforce, Inc.",
  "category": "Enterprise SaaS platform incl. Net Zero Cloud sustainability suite",
  "website": "https://www.salesforce.com/sustainability/",
  "hq": "San Francisco, California, USA",
  "founded": "1999",
  "stage": "Public - NYSE: CRM",
  "fundingSummary": "Public mega-cap SaaS",
  "headcount": "~83,823 (FY2026 headcount tracker; Salesforce official FY25 metrics schedules)",
  "headcountSource": "highperformr.ai headcount (FY26); Salesforce FY25 environmental/employee metrics PDF",
  "products": "Net Zero Cloud (carbon accounting) with Agentforce AI agents + Data Cloud integration (launched June 2025)",
  "icpFit": "competitor",
  "icpNotes": "Platform competitor in carbon accounting; potential ecosystem/channel partner",
  "climateWeekInvolvement": "Silver Partner sponsor of Climate Week NYC 2026; SVP of Impact Sunya Norman is a main-program speaker",
  "sources": [
   {
    "url": "https://www.salesforce.com/news/stories/agentforce-for-net-zero-cloud-announcement/"
   },
   {
    "url": "https://www.highperformr.ai/headcount/salesforce"
   }
  ]
 },
 {
  "lane": "A",
  "name": "Morningstar Sustainalytics",
  "category": "ESG ratings & data (note: acquired by Morningstar in 2020, NOT Moody's)",
  "website": "https://www.sustainalytics.com",
  "hq": "Amsterdam, Netherlands (US/UK presence)",
  "founded": "1992",
  "stage": "Private subsidiary of Morningstar, Inc. (NASDAQ: MORN)",
  "fundingSummary": "Acquired by Morningstar (2020); no independent rounds",
  "headcount": "701 (LinkedIn, -15.4% YoY, Jun 2026); revenue ~EUR 25.9M",
  "headcountSource": "LinkedIn company page 2026-06-28",
  "products": "ESG Risk Ratings, corporate ESG solutions, financial-materiality data for investors and companies",
  "icpFit": "partner",
  "icpNotes": "Ratings/data partner for ESG scoring integrations; small internal buying budget (headcount declining)",
  "climateWeekInvolvement": "Sustainalytics mentioned in 2 official Climate Week NYC 2026 event texts",
  "sources": [
   {
    "url": "https://linkedin.com/company/sustainalytics"
   },
   {
    "url": "https://www.sustainalytics.com/esg-data"
   },
   {
    "url": "https://marketintelligencetools.com/rankings/esg-data-providers/"
   }
  ]
 },
 {
  "lane": "A",
  "name": "S&P Global Sustainable1",
  "category": "ESG & energy-transition data/analytics division of S&P Global",
  "website": "https://www.spglobal.com/sustainable1/",
  "hq": "New York, NY, USA",
  "founded": "2021 (division; built on Trucost 2016, CSA 1999, The Climate Service 2022 acquisitions)",
  "stage": "Public parent - NYSE: SPGI (>5,000 employees; >$10B revenue)",
  "fundingSummary": "Division of public S&P Global",
  "headcount": "45,691 LinkedIn followers on Sustainable1 showcase; S&P Global >40,000 total employees",
  "headcountSource": "Verdantix Atlas vendor profile; LinkedIn showcase page",
  "products": "ESG scores, Trucost environmental data, physical climate risk (The Climate Service), CSA/DJSI",
  "icpFit": "partner",
  "icpNotes": "Data licensing partner; also a buyer for internal tooling; NYC HQ gives high accessibility",
  "climateWeekInvolvement": "S&P Global mentioned in 2 official Climate Week NYC 2026 event texts",
  "sources": [
   {
    "url": "https://www.spglobal.com/sustainable1/en"
   },
   {
    "url": "https://esgsource.com/directory/sp-global-esg"
   },
   {
    "url": "https://atlas.verdantix.com/vendors/sandp-global"
   }
  ]
 },
 {
  "lane": "A",
  "name": "Apolitical (Apolitical Group Limited)",
  "category": "Government learning network SaaS (public-sector skills platform, climate & AI focus)",
  "website": "https://apolitical.com",
  "hq": "London, UK (workforce across 8 countries incl. US, ES, BE)",
  "founded": "2015",
  "stage": "Private - grant/VC (~$13.78M total raised; last $2.22M ~2 yrs ago; CB Insights stage Grant III)",
  "fundingSummary": "~$13.78M total (CB Insights); connects 500,000+ public servants",
  "headcount": "95 (LinkedIn, 2026); revenue ~$4.1M",
  "headcountSource": "LinkedIn company page 2026; CB Insights",
  "products": "Social learning network for government: communities, courses, events; climate and AI upskilling for public servants",
  "icpFit": "partner",
  "icpNotes": "Distribution partner into government audiences; modest direct buying power",
  "climateWeekInvolvement": "Thematic Session Partner sponsor of Climate Week NYC 2026 (cw-sponsors-partners-raw.json)",
  "sources": [
   {
    "url": "https://linkedin.com/company/apolitical"
   },
   {
    "url": "https://www.cbinsights.com/company/apolitical"
   },
   {
    "url": "https://leadiq.com/c/apolitical/5a1dc3072300005200c48547"
   }
  ]
 },
 {
  "lane": "B",
  "name": "Jupiter Intelligence",
  "category": "Climate risk analytics (physical climate risk data/SaaS)",
  "website": "https://www.jupiterintel.com",
  "hq": "San Mateo, California, USA",
  "founded": "2017",
  "stage": "Private — Series C (last round: $54M Series C, 2021)",
  "fundingSummary": "~$88.5M total raised across 9 rounds; $54M Series C (Sep/Oct 2021) co-led by ClearVision Ventures and MPower Partners. No later equity round found as of 2026-09-10.",
  "headcount": "~53 (LinkedIn company page); LeadIQ lists 51-200",
  "headcountSource": "LinkedIn company profile https://linkedin.com/company/jupiterintel (~53 employees, -11.7% YoY, retrieved 2026-09-10); LeadIQ employee directory https://leadiq.com/c/jupiter-intelligence/5b1547bc350000bb0082764a/employee-directory (51-200 range). Company does not publish staff numbers.",
  "products": "Decision-grade physical climate risk intelligence: Jupiter RiskSignal, Adaptation Hub, Entity Modeling, MetricEngine, Compliance Hub, MRM Accelerator and Site Intelligence; asset-, portfolio- and entity-level flood, heat, fire, wind, hail and water-stress analytics for banks, asset managers/private equity, infrastructure and industrial corporates, and governments.",
  "icpFit": "competitor",
  "icpNotes": "Direct competitor for a B2B climate risk software/data/AI seller: sells physical-risk analytics into financial institutions and corporates, overlapping the same buyer (risk, sustainability, investment committees). Low likelihood of buying a competing analytics platform, but a plausible data-supply or co-selling partner for adjacent capabilities (adaptation planning, disclosure workflows).",
  "climateWeekRole": "Event host (2 events) + speaker org + multiple description mentions. Hosts 'Beyond the Heat Map: How Leading Investors Are Building Climate-Resilient Portfolios' (Wed Sep 23, 2026, 08:00, In-person/Private; host_hint 'Jupiter Intelligence and Impax Asset Management') and 'Affordable Resilience: Turning Climate Risk into Long-Term Value Through Adaptation and Investment' (Thu Sep 24, 2026, 09:00, Private; host_hint 'Jupiter Intelligence & Arcadis'). CEO Rich Sorkin is a listed speaker on 'Everyone's Reporting Climate Risk. Who's Deciding? From Disclosed Risk to Defended Assets' (Wed Sep 23, 2026, 09:30, Private). 3 event-description mentions in task2-description-mining.json. candidate-universe records it as event-host (2 events).",
  "sources": [
   {
    "title": "Jupiter Intelligence — Company",
    "url": "https://www.jupiterintel.com/company"
   },
   {
    "title": "Jupiter Intelligence — Products",
    "url": "https://www.jupiterintel.com/products"
   },
   {
    "title": "Axios — Excl: Jupiter Intelligence raises $54 million (Series C, Oct 2021)",
    "url": "https://www.axios.com/2021/10/21/jupiter-intelligence-raises-54million-climate-risk"
   },
   {
    "title": "Jupiter Intelligence — Announces $54M in New Funding",
    "url": "https://www.jupiterintel.com/blog/jupiter-announces-54-million-in-new-funding"
   },
   {
    "title": "CB Insights — Jupiter Intelligence funding (total $88.53M)",
    "url": "https://www.cbinsights.com/company/jupiter-intelligence/financials"
   },
   {
    "title": "LinkedIn — Jupiter Intelligence (headcount)",
    "url": "https://linkedin.com/company/jupiterintel"
   },
   {
    "title": "LeadIQ — Jupiter Intelligence employee directory",
    "url": "https://leadiq.com/c/jupiter-intelligence/5b1547bc350000bb0082764a/employee-directory"
   }
  ]
 },
 {
  "lane": "B",
  "name": "Climate X",
  "category": "Climate risk analytics / physical risk data (SaaS)",
  "website": "https://www.climate-x.com",
  "hq": "London, United Kingdom",
  "founded": "2020",
  "stage": "Private — Series A (last round: $18M Series A, Jun 2024)",
  "fundingSummary": "~$24.6M-$26M total raised; $18M Series A (announced 26 Jun 2024) led by GV (Google Ventures) to price physical climate risk to buildings/infrastructure. Customers cited include Legal & General, CBRE, Virgin Money, Carlyle, European Investment Bank.",
  "headcount": "89 (LinkedIn company page, +12.4% YoY)",
  "headcountSource": "LinkedIn company profile https://linkedin.com/company/climate-x ('employs 89 people, +12.4% YoY, +11 people', workforce across 7 countries, retrieved 2026-09-10).",
  "products": "Climate risk software: Spectra (translates physical climate risk into financial loss metrics at portfolio and asset level), Adapt (adaptation CapEx and ROI), Carta (asset-level mapping across 18.7M public/private companies), Adaptation Finance and an Infrastructure Climate Risk Screener. Aligned to TCFD, IFRS S2, SB261; targeted at banking, real estate, private equity/asset management, insurance and consultancies.",
  "icpFit": "competitor",
  "icpNotes": "Direct competitor: sells physical-risk data/analytics to financial institutions (G-SIBs, asset managers) — the same buying centre a climate software/data/AI seller would target. Unlikely buyer of competing analytics; possible partner where a seller needs peril-level data or non-overlapping coverage.",
  "climateWeekRole": "No verified company involvement. The coordinator noted 1 event mention, but the only artifact match is the phrase 'climate x fashion leaders' in the description of the student-run 'Sustainable Fashion Scholars Ideation Day' (Tue Sep 22, 2026, 12:00, Public) — a false positive, not the company (task2-description-mining.json; confirmed by keyword re-scan of all 838 events). No sponsor/partner entry, no event-host role, no speaker.",
  "sources": [
   {
    "title": "Climate X — homepage/product (Spectra, Adapt, Carta)",
    "url": "https://www.climate-x.com/"
   },
   {
    "title": "Climate X — Series A press release ($18m, GV-led, Jun 2024)",
    "url": "https://www.climate-x.com/articles/press-releases/series-a"
   },
   {
    "title": "TechCrunch — Climate X raises $18M Series A",
    "url": "https://techcrunch.com/2024/06/26/climate-x-founders-who-mortgaged-their-houses-to-stay-afloat-now-raise-a-18-million-series-a/"
   },
   {
    "title": "Tech.eu — Climate X raises $18M to assess climate risk for property investors",
    "url": "https://tech.eu/2024/06/26/climate-x-raises-18m-to-assess-climate-risk-for-property-investors/"
   },
   {
    "title": "LinkedIn — Climate X (headcount, total funding)",
    "url": "https://linkedin.com/company/climate-x"
   },
   {
    "title": "Indexed.vc — Climate X company profile ($26M raised)",
    "url": "https://indexed.vc/companies/climate-x"
   }
  ]
 },
 {
  "lane": "B",
  "name": "Carbon Mapper",
  "category": "Nonprofit satellite/airborne methane & CO2 MRV data",
  "website": "https://carbonmapper.org",
  "hq": "Pasadena, California, USA",
  "founded": "2020",
  "stage": "Nonprofit 501(c)(3) — philanthropic/donor funded, no equity rounds",
  "fundingSummary": "$100M total funding (LinkedIn). Funded by a coalition including Bloomberg Philanthropies (a $25M commitment in Oct 2021), High Tide Foundation, the State of California, NASA JPL, Planet, University of Arizona, ASU and RMI. Tanager-1, the coalition's first methane/CO2-sensing satellite, launched 16 Aug 2024.",
  "headcount": "43 (LinkedIn company page, +36.1% YoY); LeadIQ lists 11-50",
  "headcountSource": "LinkedIn company profile https://linkedin.com/company/carbon-mapper ('employs 43 people, +36.1% YoY, +13 people', $100M total funding, retrieved 2026-09-10); LeadIQ employee directory https://leadiq.com/c/carbon-mapper/63a3441a99142b48fdc14d06/employee-directory (11-50 range). Audited financial statements (FY2025) are public at assets.carbonmapper.org.",
  "products": "Methane and CO2 point-source detection and quantification: Tanager satellite constellation (JPL imaging spectrometer), airborne remote sensing surveys, and a public data portal publishing facility-scale plume and emission-rate data to drive emissions reductions.",
  "icpFit": "partner",
  "icpNotes": "Mission-driven data producer, not a commercial software buyer — but a strong partner: it supplies open methane/CO2 MRV data that a climate data/AI seller could integrate or co-market. Existing funders (Bloomberg Philanthropies, High Tide) and coalition members are better software buyers than Carbon Mapper itself.",
  "climateWeekRole": "Description mention / event participant (1 mention). 'From Finding to Fixing: Accelerating Action on Methane Super-Emitters' (Tue Sep 22, 2026, 13:30, In-person, Public) description: 'Join Carbon Mapper, along with other experts, to discuss what is needed to increase action on methane super-emitters' (task2-description-mining.json). Not a sponsor/partner, event host, or speaker-org in the artifacts.",
  "sources": [
   {
    "title": "Carbon Mapper — About",
    "url": "https://carbonmapper.org/about"
   },
   {
    "title": "Carbon Mapper — Bloomberg Philanthropies commits $25M (Oct 2021)",
    "url": "https://carbonmapper.org/articles/bloomberg-philanthropies"
   },
   {
    "title": "Reuters — Group backed by Bloomberg, NASA launches first methane-hunting satellite (Aug 2024)",
    "url": "https://www.reuters.com/science/group-backed-by-bloomberg-nasa-launches-its-first-methane-hunting-satellite-2024-08-16/"
   },
   {
    "title": "NASA JPL — NASA-designed greenhouse gas detection instrument launches",
    "url": "https://www.jpl.nasa.gov/news/nasa-designed-greenhouse-gas-detection-instrument-launches/"
   },
   {
    "title": "LinkedIn — Carbon Mapper (headcount, total funding)",
    "url": "https://linkedin.com/company/carbon-mapper"
   },
   {
    "title": "Carbon Mapper — FY2025 audited financial statements",
    "url": "https://assets.carbonmapper.org/documents/Carbon%20Mapper%20Audit%20Report%20August%202025%20-%20Final%20Signed.pdf"
   }
  ]
 },
 {
  "lane": "B",
  "name": "Kayrros",
  "category": "Satellite-based environmental/energy intelligence and data",
  "website": "https://www.kayrros.com",
  "hq": "Paris, France",
  "founded": "2016",
  "stage": "Acquired — Energy Aspects agreed to acquire Kayrros (12 Mar 2026) and completed the deal (21 May 2026)",
  "fundingSummary": "$78.03M raised across 8 rounds (CB Insights); last standalone round was EUR40M (Mar 2022), including participation by the French government via French Tech Souverainete. Acquired in 2026 by UK market-data firm Energy Aspects (which previously acquired OilX, INAS and TankWatch).",
  "headcount": "95 (LinkedIn company page)",
  "headcountSource": "LinkedIn company profile https://linkedin.com/company/kayrros ('employs 95 people', annual revenue ~$4M, retrieved 2026-09-10). No company-reported headcount published.",
  "products": "Satellite/geospatial environmental intelligence: Methane Watch (near-real-time methane super-emitter detection for operators, regulators and financial institutions), energy supply/demand and asset observation analytics, FireWatch wildfire monitoring; supported implementation of the UNEP-MARS methane programme.",
  "icpFit": "competitor",
  "icpNotes": "Competitor in satellite-derived emissions/energy data and analytics; sells into energy companies, financial institutions and regulators. Post-acquisition it is being folded into Energy Aspects, making it a consolidation event rather than a software buyer. Potential data-supply partner where coverage complements a seller's offering.",
  "climateWeekRole": "No involvement identified in the Climate Week NYC 2026 artifacts: zero mentions across all 838 event records, the 39 sponsors/partners and the 70-speaker list (keyword scans of cw-events-raw.json, cw-sponsors-partners-raw.json, cw-speakers-raw.json, task2-description-mining.json). Assigned with no Climate Week evidence.",
  "sources": [
   {
    "title": "Kayrros — Methane Watch for Operators",
    "url": "https://www.kayrros.com/products/methane-watch-for-operators/"
   },
   {
    "title": "Kayrros — Methane Watch (regulators/financial institutions)",
    "url": "https://methanewatch.kayrros.com/"
   },
   {
    "title": "Kayrros — €40M funding round press release (Mar 2022)",
    "url": "https://www.kayrros.com/press_release/kayrros-the-french-climate-tech-leader-raises-e40-million-in-funding/"
   },
   {
    "title": "Energy Aspects — Agrees to acquire Kayrros (12 Mar 2026)",
    "url": "https://www.energyaspects.com/resources/insights/energy-aspects-to-acquire-satellite-data-and-analytics-company-kayrros"
   },
   {
    "title": "Energy Aspects — Completes acquisition of Kayrros (21 May 2026)",
    "url": "https://www.energyaspects.com/resources/insights/energy-aspects-completes-acquisition-of-kayrros"
   },
   {
    "title": "CB Insights — Kayrros financials (total raised $78.03M; acquired)",
    "url": "https://www.cbinsights.com/company/kayrros/financials"
   },
   {
    "title": "LinkedIn — Kayrros (headcount)",
    "url": "https://linkedin.com/company/kayrros"
   }
  ]
 },
 {
  "lane": "B",
  "name": "Wood Mackenzie",
  "category": "Energy & natural resources research, data and analytics (information services)",
  "website": "https://www.woodmac.com",
  "hq": "Edinburgh, Scotland, United Kingdom",
  "founded": "1973",
  "stage": "Private — PE-owned; acquired by Veritas Capital from Verisk for $3.1B (closed 2 Feb 2023)",
  "fundingSummary": "Not venture-funded: formerly a Verisk (Nasdaq: VRSK) business, sold to Veritas Capital for $3.1B (announced Oct 2022, closed Feb 2023). Currently a Veritas portfolio company; acquired LandGate in Jun 2026.",
  "headcount": "~2,924 (Revelio Labs, Mar 2026) / 1,974 (LinkedIn company page)",
  "headcountSource": "Revelio Labs workforce data, published Aug 2026: 'approximately 2,924 total employees worldwide as of March 2026' https://www.reveliolabs.com/companies/wood-mackenzie/employees; LinkedIn company profile https://linkedin.com/company/wood-mackenzie (1,974 employees, +7.4% YoY). Figures differ by methodology; both cited, retrieved 2026-09-10.",
  "products": "Subscription research, data, analytics and consulting covering oil & gas, power and renewables, chemicals, metals & mining and energy transition scenarios (Wood Mackenzie Lens platform), plus real-time asset and supply-chain analytics; increasingly AI/data-product oriented under PE ownership.",
  "icpFit": "partner",
  "icpNotes": "Research/data incumbent, not a typical software buyer — but a strong partner/channel for a climate data or AI seller (co-branded research, embedded datasets, joint enterprise sales). Partly competitive on energy-transition data. Buys selectively: data assets and analytics tooling (e.g., LandGate acquisition) rather than competing platforms.",
  "climateWeekRole": "Speaker org + 1 description mention. Ed Crooks (Vice Chair Americas and host of the Energy Gang podcast, Wood Mackenzie) is a listed Climate Week NYC 2026 speaker (cw-speakers-raw.json, 70 speakers; candidate-universe role: speaker-org). Cited as a data source in the description of 'Why just building factories isn't cutting it: a roundtable discussion' (Tue Sep 22, 2026, 07:00, Private) — '(Wood Mackenzie, Q2 2025)'. Not a sponsor/partner or event host.",
  "sources": [
   {
    "title": "Wood Mackenzie — website",
    "url": "https://www.woodmac.com"
   },
   {
    "title": "Wood Mackenzie — Veritas Capital completes acquisition (Feb 2023)",
    "url": "https://www.woodmac.com/press-releases/veritas-capital-completes-acquisition-of-wood-mackenzie/"
   },
   {
    "title": "Reuters — Verisk to sell Wood Mackenzie to PE firm for $3.1 bln",
    "url": "https://www.reuters.com/markets/commodities/verisk-sell-wood-mackenzie-unit-pe-firm-31-bln-2022-10-31/"
   },
   {
    "title": "Gibson Dunn — Wood Mackenzie acquisition of LandGate (Jun 2026)",
    "url": "https://www.gibsondunn.com/gibson-dunn-advised-veritas-capitals-wood-mackenzie-on-acquisition-of-landgate/"
   },
   {
    "title": "Revelio Labs — Wood Mackenzie employee count (~2,924, Mar 2026)",
    "url": "https://www.reveliolabs.com/companies/wood-mackenzie/employees"
   },
   {
    "title": "LinkedIn — Wood Mackenzie (headcount)",
    "url": "https://linkedin.com/company/wood-mackenzie"
   }
  ]
 },
 {
  "lane": "B",
  "name": "BloombergNEF",
  "category": "Energy transition research/data (strategic research provider; division of Bloomberg L.P.)",
  "website": "https://about.bnef.com",
  "hq": "London, United Kingdom (division of Bloomberg L.P., HQ New York)",
  "founded": "2004",
  "stage": "Private — wholly owned research division of Bloomberg L.P. (not separately funded)",
  "fundingSummary": "No standalone funding; BNEF (founded 2004 as New Energy Finance) was acquired by Bloomberg L.P. in 2010 and operates as Bloomberg's energy-transition research arm, monetised via subscriptions and Bloomberg Terminal distribution.",
  "headcount": "null",
  "headcountSource": "Headcount could not be verified: BNEF does not publish staff numbers, and its LinkedIn page lists no employee count. It is a division of Bloomberg L.P., so any standalone figure is an estimate. A third-party directory lists ~276 employees (aVenture, 2024) https://aventure.vc/companies/bloombergnef-london-uk — unverified, so headcount left null.",
  "products": "Subscription research, proprietary datasets and models on power, transport, industry, buildings, agriculture and commodities, plus long-run energy transition scenarios, clean energy/EV/battery cost curves, Climatescope and BNEF summit events; distributed via the Bloomberg Terminal.",
  "icpFit": "partner",
  "icpNotes": "Analyst/research house and media-style authority rather than a software buyer; overlaps a data seller on energy-transition datasets. Best treated as a partner/channel (co-branded insight, data licensing, event and audience access) and as a competitor for data subscription budget — not a target account for climate software/AI.",
  "climateWeekRole": "1 description mention via an event speaker. 'Powering AI: who wins when demand outpaces the grid?' (Mon Sep 21, 2026, 16:30, In-person, Private) lists Stephanie Diaz, Technology & Innovation Senior Associate, Bloomberg New Energy Finance (BloombergNEF) (cw-events-raw.json; task2-description-mining.json). Note: the coordinator described BloombergNEF as 'speaker org + 1 mention', but BloombergNEF does not appear as a standalone entry in cw-speakers-raw.json (70 entries); its only presence is this event description. Not a sponsor/partner or event host.",
  "sources": [
   {
    "title": "BloombergNEF — About",
    "url": "https://about.bnef.com/about/"
   },
   {
    "title": "BloombergNEF — What we do",
    "url": "https://about.bnef.com/what-we-do/"
   },
   {
    "title": "BloombergNEF — Overview deck (founded 2004); PSME",
    "url": "https://psme.org.pl/wp-content/uploads/2024/10/BNEF_Overview_2024.pdf"
   },
   {
    "title": "LinkedIn — BloombergNEF (founded 2004, HQ London)",
    "url": "https://linkedin.com/company/bloombergnef"
   },
   {
    "title": "CB Insights — BloombergNEF profile",
    "url": "https://www.cbinsights.com/company/new-energy-finance1"
   },
   {
    "title": "aVenture — BloombergNEF (unverified ~276 employees)",
    "url": "https://aventure.vc/companies/bloombergnef-london-uk"
   }
  ]
 },
 {
  "lane": "B",
  "name": "Ember",
  "category": "Energy/climate data think tank (open electricity data and policy analysis)",
  "website": "https://ember-energy.org",
  "hq": "London, United Kingdom",
  "founded": "2020",
  "stage": "Nonprofit — not-for-profit think tank (community interest company in England & Wales), grant/donor funded",
  "fundingSummary": "Philanthropy-funded: no equity or VC rounds. Reported to rely in part on overseas climate-focused donors (The Telegraph, 3 Jul 2026); annual revenue ~$24M (LinkedIn). Rebranded in 2020 from the Sandbag Climate Campaign (founded 2008).",
  "headcount": "75 (LinkedIn company page, +23.2% YoY); an Aug 2025 job ad references an ~80-person team across 19 countries",
  "headcountSource": "LinkedIn company profile https://uk.linkedin.com/company/emberenergyresearch ('employs 75 people, +23.2% YoY, +33 people', revenue ~$24M, retrieved 2026-09-10); Ember Managing Director job description (Aug 2025) referencing an '80-person Ember team across 19 countries' https://ember-energy.org/app/uploads/2025/08/Managing-Director-Job-description-2025-for-Website.pdf.",
  "products": "Free/open electricity system data and analysis: global electricity data explorer and country dashboards, annual Global Electricity Review, coal-mine methane tracking, and policy insights/campaigns aimed at accelerating the clean electricity transition.",
  "icpFit": "partner",
  "icpNotes": "Not a software buyer — a data-owning nonprofit think tank (weak-fit as a purchaser of B2B climate software). Strong as a partner/data and credibility channel: its open electricity datasets and policy audience can complement a seller's product, and it influences the same corporate/utility buying centres. Note the data it publishes is free, so there is no data-licensing revenue path.",
  "climateWeekRole": "Speaker org only. Daan Walter, Principal, Ember is a listed Climate Week NYC 2026 speaker (cw-speakers-raw.json, 70 entries; candidate-universe role: speaker-org). No description mentions, no event-host role, and no sponsor/partner entry in the artifacts. DISCREPANCY: the coordinator brief describes Ember as a 'Media Partner sponsor'; the enumerated sponsors/partners artifact (cw-sponsors-partners-raw.json, 39 entries; Media Partner tier = JCDecaux, 50 Shades of Green, HiImpact, Newsweek, Project Syndicate, Reuters Plus) does not include Ember — treat the Media Partner claim as unverified in-artifact.",
  "sources": [
   {
    "title": "Ember — About us",
    "url": "https://ember-energy.org/about/"
   },
   {
    "title": "Ember — homepage (open electricity data)",
    "url": "https://ember-energy.org/"
   },
   {
    "title": "Ember — H1 2024 Impact Report",
    "url": "https://ember-energy.org/app/uploads/2024/12/Impact-Report-H1-2024-PDF-21-MB.pdf"
   },
   {
    "title": "Ember — Managing Director job description (Aug 2025, ~80-person team)",
    "url": "https://ember-energy.org/app/uploads/2025/08/Managing-Director-Job-description-2025-for-Website.pdf"
   },
   {
    "title": "LinkedIn — Ember (headcount, revenue)",
    "url": "https://uk.linkedin.com/company/emberenergyresearch"
   },
   {
    "title": "Influence Watch — Ember (structure: founded 2008 as Sandbag, rebranded 2020)",
    "url": "https://www.influencewatch.org/non-profit/ember/"
   },
   {
    "title": "The Telegraph via Daily Sceptic — Ember partly funded by overseas climate-focused donors (Jul 2026)",
    "url": "https://dailysceptic.org/2026/07/03/milibands-favourite-net-zero-think-tank-funded-by-foreign-cash/"
   }
  ]
 },
 {
  "lane": "B",
  "name": "STX Group",
  "category": "Environmental commodities trading & corporate climate solutions",
  "website": "https://stxgroup.com",
  "hq": "Amsterdam, Netherlands",
  "founded": "2005",
  "stage": "Private — PE-controlled; Partners Group acquired a controlling stake (late 2021)",
  "fundingSummary": "Not venture-funded; majority controlled by Partners Group since late 2021 (per ownership analyses), following the 2021 majority acquisition of Vertis. Financed by a renewable environmental commodities borrowing-base credit facility: renewed up to EUR290M (18 Nov 2025), previously expanded to EUR375M (Sep 2024). LinkedIn lists EUR150.2M total funding with 1 prior round.",
  "headcount": "407 (LinkedIn company page, -1.1% YoY)",
  "headcountSource": "LinkedIn company profile https://linkedin.com/company/stxgroup ('employs 407 people, -1.1% YoY, -6 people', revenue ~$180.4M, retrieved 2026-09-10); FundedIQ and CB Insights list 251-500 employees. Company does not publish a staff number.",
  "products": "Trading in environmental commodities (renewable/energy attribute certificates, EU ETS allowances and carbon credits, biogas/biomethane, biofuels, energy efficiency), corporate climate solutions and advisory via STRIVE by STX, regulated emissions trading via Vertis (MiFID II), and Marine Olie (biofuel feedstock trading); ClimateTech client platform.",
  "icpFit": "buyer",
  "icpNotes": "Genuine buyer profile: a capital-markets-adjacent trading and advisory firm that needs market data, pricing/risk analytics and enterprise tooling (its own 'ClimateTech' platform), and that sells decarbonisation services to corporates — a natural account for a climate data/analytics/AI seller, and also a partner/channel into corporate energy buyers (STRIVE advisory).",
  "climateWeekRole": "Event host (2 events) + moderator + description mention. Co-hosts 'What's Next for Data Center Decarbonization? Navigating the Many Facets to Reach Net Zero in a Volatile Market' with iMasons Climate Accord (Tue Sep 22, 2026, 17:00, In-person, Public) — 'Join STX Group and iMasons Climate Accord during Climate Week NYC...'. Also hosts and moderates 'Unlocking Value Chain Decarbonization with Market-Based Instruments' (Tue Sep 22, 2026, 16:00, Public) — 'Moderated by Jordan Woll (STX Group)'. candidate-universe lists STX Group as event-host (2 events); no sponsor/partner tier or speaker-org entry.",
  "sources": [
   {
    "title": "STX Group — About us",
    "url": "https://stxgroup.com/about-us/"
   },
   {
    "title": "STX Group — homepage / brands (STRIVE, Vertis, Marine Olie)",
    "url": "https://stxgroup.com/"
   },
   {
    "title": "STX Group — Credit facility renewed up to EUR290M (Nov 2025)",
    "url": "https://stxgroup.com/media-release/stx-group-refinances-its-environmental-commodities-credit-facility/"
   },
   {
    "title": "STX Group — Environmental credit facility expanded to EUR375M (Sep 2024)",
    "url": "https://stxgroup.com/media-release/stx-group-expands-the-environmental-credit-facility-up-to-eur-375-million/"
   },
   {
    "title": "LinkedIn — STX Group (headcount, funding)",
    "url": "https://linkedin.com/company/stxgroup"
   },
   {
    "title": "Business Model Canvas Template — Who owns STX Group (Partners Group controlling stake, 2021)",
    "url": "https://businessmodelcanvastemplate.com/blogs/owners/stx-group-who-owns"
   },
   {
    "title": "FundedIQ — STX Group funding & employees",
    "url": "https://fundediq.co/stx-group-stxgroup-com-funding/"
   }
  ]
 },
 {
  "lane": "C",
  "name": "Crux Climate (Crux Climate Inc., dba Crux)",
  "category": "Climate fintech / capital markets software (transferable clean-energy tax credits, project finance)",
  "website": "https://www.crux.com (formerly cruxclimate.com)",
  "hq": "New York, NY (technical.ly); dual D.C./N.Y. presence — LinkedIn lists Washington, D.C. as primary with offices in Dover and New York",
  "founded": "2023 (launched publicly April 2023; founders Alfred Johnson and Allen Kramer, previously founded/sold Mobilize)",
  "stage": "Private, VC-backed — Series B (April 2025); earlier a16z-led Series A",
  "fundingSummary": "$4.25M seed extension (Jun 2023) + $18.2M Series A led by Andreessen Horowitz/a16z (Jan 2024) + $50M Series B led by Lowercarbon Capital with Liberty Mutual Strategic Ventures, MassMutual Ventures and OMERS Ventures (Apr 2025); approx. $72M+ disclosed total. No 2026 round found in search.",
  "headcount": "91",
  "headcountSource": "LinkedIn company page for Crux/Crux Climate Inc. reports ~91 employees (profile snapshot indexed 25 Jun 2026): https://linkedin.com/company/cruxclimate. Third-party directories disagree (ZoomInfo lists 11-50). Treat 91 as a LinkedIn approximation, not a company-reported figure; Crunchbase/PitchBook login-gated.",
  "products": "Capital-markets platform for the clean economy: marketplace and software to originate, price, transact and manage transferable clean-energy tax credits (IRA credits), plus capital-raise project finance tooling, market intelligence/pricing data, and advisory/investment services. Originally the 'marketplace for IRA tax credits'; now positioning as broader 'capital platform for the clean economy'.",
  "icpFit": "partner",
  "icpNotes": "Crux is itself a climate fintech/software company, so it is unlikely to buy much third-party climate software or data (light appetite for market-data feeds and analytics). Its value to a B2B climate software/data/AI seller is as an ecosystem/co-sell partner: Crux's customer base is exactly the buyer set a climate seller wants — clean-energy project developers, manufacturers, corporate tax-credit buyers, and tax-equity/tax-credit investors and banks. Partner/channel fit rather than buyer; indirect competitor in 'capital-markets data' only.",
  "climateWeekRole": "LIKELY FALSE POSITIVE — no verified involvement. task2-description-mining.json records 'Crux Climate' with 1 mention in event 'meet-the-wonks-behind-the-wins-a-networking-happy-hour' (2026-09-22, 113 W 24 St). Reading that event's description shows the participant is 'Crux Alliance, ReNew2030, Global Grids Catalyst, and Growald Climate Fund' — i.e. the unrelated philanthropic policy network Crux Alliance (candidate universe: event-host, 5 events hosted), NOT Crux Climate Inc. Crux Climate appears in zero sponsor tiers, zero speaker records, and zero self-hosted events. Recommend the parent treat 'Crux Climate' as a mismatch and re-attribute the mining hit to Crux Alliance.",
  "sources": [
   {
    "title": "Crux — What Our $18.2M Series A Means For Our Partners",
    "url": "https://www.cruxclimate.com/insights/series-a-roadmap"
   },
   {
    "title": "Axios — Exclusive: Crux nets $18M for clean energy credits, led by a16z",
    "url": "https://www.axios.com/pro/climate-deals/2024/01/30/crux-18-million-andreesen-horowitz-tax-equity"
   },
   {
    "title": "Crux — What our $50M Series B means for Crux partners",
    "url": "https://www.crux.com/blog/crux-announces-50m-series-b-funding-round"
   },
   {
    "title": "Technical.ly — a16z-backed clean energy startup Crux lands $50 million (year founded 2023; HQ New York)",
    "url": "https://technical.ly/entrepreneurship/crux-series-b-alfred-johnson/"
   },
   {
    "title": "Crux — Crux raises $4.25 million in rapid seed extension (Jun 2023)",
    "url": "https://www.crux.com/blog/seed-extension"
   },
   {
    "title": "Crux — About (capital platform for the clean economy)",
    "url": "https://www.crux.com/about"
   },
   {
    "title": "LinkedIn — Crux (Crux Climate Inc.) company page, headcount ~91 (~Jun 2026)",
    "url": "https://linkedin.com/company/cruxclimate"
   },
   {
    "title": "Climate Week NYC event used as mining evidence: 'Meet the Wonks Behind the Wins' (Crux Alliance, not Crux Climate)",
    "url": "https://www.climateweeknyc.org/event-search/meet-the-wonks-behind-the-wins-a-networking-happy-hour?hsLang=en"
   }
  ]
 },
 {
  "lane": "C",
  "name": "Octopus Energy Group / Kraken Technologies",
  "category": "Energy tech platform (retail energy + grid/utility SaaS + AI/ML; renewable generation)",
  "website": "https://octopusenergy.com (group) / https://kraken.tech (Kraken platform)",
  "hq": "London, United Kingdom (both Octopus Energy Group and Kraken Technologies)",
  "founded": "Octopus Energy Group 2015; Kraken Technologies platform launched 2017 (Wikipedia infobox; PitchBook lists 2011 legacy entity)",
  "stage": "Private. Octopus Energy Group is a private unicorn (valuation $9bn after Dec 2024 raise); Kraken was spun out as a standalone private company in Dec 2025 following a $1bn round led by D1 Capital Partners (valuation $8.65bn).",
  "fundingSummary": "Octopus Energy Group: ~$2.9bn raised to date; $370M added Dec 2024 via existing shareholders GIM (Aware Super et al.) lifting valuation ~15% to $9bn; earlier rounds incl. December 2023 round; group is profitable (FY24 net profit £83m on £12.4bn revenue). Kraken standalone: $1bn first external round Dec 2025 led by D1 Capital Partners with Ontario Teachers' Pension Plan, Fidelity International and Durable Capital Partners, valuing Kraken at $8.65bn; Kraken had ~$500m contracted annual revenue (growing 4x in 3 years) at spin-off.",
  "headcount": "5491",
  "headcountSource": "Revelio Labs workforce data: Octopus Energy Ltd ~5,491 total employees worldwide as of March 2026 (published Aug 2026): https://www.reveliolabs.com/companies/octopus-energy/employees. Broader group aggregate reported elsewhere as ~11,000 (Silicon Valley Investclub tear-sheet, Dec 2025) across 27 countries. Kraken Technologies separately reported at ~2,000 employees (Wikipedia infobox citing company data): https://en.wikipedia.org/wiki/Kraken_Technologies",
  "products": "Octopus Energy Group: retail electricity/gas supply to 7.2M+ (11M+ household) customer accounts, smart/EV tariffs (Intelligent Octopus, Agile), renewables generation and investment, heat pumps, EV charging (Electroverse). Kraken Technologies: cloud-native utility operating system licensed to 40+ energy suppliers/generators globally (EDF, E.ON, National Grid, Origin, etc.) covering customer management, billing, CRM, field ops, and AI/ML-driven customer service and load optimisation; contracted revenue ~$500m ARR at spin-off.",
  "icpFit": "partner (with competitor overlap)",
  "icpNotes": "Kraken is a global distribution channel to utilities, retailers and grid operators — a strong partner/co-sell or integration target for energy data and AI tooling. But Kraken builds much of its energy data/analytics/AI in-house, so it is also a partial competitor for utility-facing energy software, and Octopus Energy itself (a large retailer/generator) is a plausible enterprise buyer of grid/market-data and sustainability reporting tools. Net: partner-first, with competitive overlap in utility energy software.",
  "climateWeekRole": "MINIMAL / INDIRECT. Description-mining records 'Octopus Energy' 1 mention and 'Kraken (Octopus)' 1 mention. (1) 'Building sustainable cities – Clean Energy Edition: London & NYC' (2026-09-22, hosted by London & Partners and London Stock Exchange Group) lists 'Kraken Energy' among the speakers heard from. (2) 'The 35% Moment: What Will It Take to Electrify the Global Economy by 2035?' (2026-09-22) is co-presented by the Climate Knowledge Initiative at Columbia Business School and Centre for Net Zero, 'a nonprofit research institute founded by Octopus Energy Group'. No official sponsor tier, no hosted events, no speaker-record entry (cw-speakers-raw.json has no Octopus/Kraken speaker) — involvement is partner/affiliate-level, not sponsoring.",
  "sources": [
   {
    "title": "Kraken — Octopus Energy Group to spin out Kraken at valuation of $8.65bn (Dec 2025)",
    "url": "https://www.kraken.tech/press-releases/octopus-energy-group-to-spin-out-kraken-at-valuation-of-usd8-65bn"
   },
   {
    "title": "Octopus Energy — Octopus Energy's valuation increases to $9bn following further commitments from existing investors (Dec 2024)",
    "url": "https://octopus.energy/press/Octopus-Energy-valuation-increases-to-9bn-following-further-commitments-from-existing-investors/"
   },
   {
    "title": "Octopus Energy — Octopus Energy Group to spin off Kraken (Sept 2025; $500m contracted revenue)",
    "url": "https://octopus.energy/press/octopus-energy-group-to-spin-off-kraken/"
   },
   {
    "title": "Reuters — Britain's Octopus Energy to spin out Kraken at $8.65 billion valuation",
    "url": "https://www.reuters.com/business/energy/uks-octopus-energy-nears-kraken-stake-sale-sky-news-reports-2025-12-29/"
   },
   {
    "title": "CNBC — Octopus Energy to spinoff AI unit Kraken at $8.65 billion valuation",
    "url": "https://www.cnbc.com/2025/12/30/octopus-energy-to-spinoff-ai-unit-kraken-at-8point65-billion-valuation.html"
   },
   {
    "title": "Wikipedia — Kraken Technologies (founded 2017; ~2,000 employees; 40+ utility licences; parent Octopus Energy)",
    "url": "https://en.wikipedia.org/wiki/Kraken_Technologies"
   },
   {
    "title": "Revelio Labs — Octopus Energy number of employees (~5,491, Mar 2026)",
    "url": "https://www.reveliolabs.com/companies/octopus-energy/employees"
   },
   {
    "title": "Octopus Energy Group Limited — Annual Report and Financial Statements FY25",
    "url": "https://octopusenergy.group/static/documents/OEGL_Financial_statements_Annual_Report_FY25.pdf"
   },
   {
    "title": "Climate Week NYC event evidence: 'Building sustainable cities – Clean Energy Edition' (Kraken Energy listed)",
    "url": "https://www.climateweeknyc.org/event-search/building-sustainable-cities-clean-energy-edition-london-nyc-innovation-investment-and-collaboration?hsLang=en"
   },
   {
    "title": "Climate Week NYC event evidence: 'The 35% Moment' (Centre for Net Zero founded by Octopus Energy Group)",
    "url": "https://www.climateweeknyc.org/event-search/the-35-moment-what-will-it-take-to-electrify-the-global-economy-by-2035?hsLang=en"
   }
  ]
 },
 {
  "lane": "C",
  "name": "Scale AI (Scale AI, Inc.)",
  "category": "AI data / data-labeling (data engine, evaluation, RLHF); not a climate company",
  "website": "https://scale.com",
  "hq": "San Francisco, California, United States",
  "founded": "2016",
  "stage": "Private, late-stage; Meta made a $14.3bn strategic investment in June 2025 valuing Scale at over $29bn (founder/CEO Alexandr Wang departed to Meta; Jason Droege became CEO).",
  "fundingSummary": "$1B Series F (May 2024) at ~$13.8B valuation led by Accel with Amazon, Meta, Nvidia, Y Combinator participation; plus earlier rounds (Series A-E, ~$600M+). June 2025: $14.3bn strategic investment from Meta Platforms (Nasdaq: META) valuing Scale at >$29bn. Total capital raised across rounds is not fully disclosed (~$1.6B+ in equity before the Meta deal); the Meta transaction is an investment, not an acquisition.",
  "headcount": "1200",
  "headcountSource": "Full-time headcount of ~1,200 in 2026 (JobsByCulture research, updated April 2026): https://jobsbyculture.com/blog/scale-ai-employee-count-2026, consistent with Business Insider's July 2025 report of a '1,400-person workforce' before a 14% layoff (~200 full-time roles plus ~500 contractors): https://www.businessinsider.com/scale-ai-layoffs-hit-genai-team-after-meta-deal-2025-7. Note: Revelio Labs counts ~5,775 total workers (Mar 2026) and LinkedIn ~3,751 — these include global contract/tasker networks and are NOT full-time employee counts. Use ~1,200 full-time as the best available approximation.",
  "products": "AI data foundry: data labeling/annotation, RLHF and model evaluation, synthetic and expert data, red-teaming, and datasets for generative AI, autonomous vehicles, robotics and government/defense (Scale Donovan, Scale Studio, Scale Rapid). Enterprise data/AI infrastructure services sold to AI labs, enterprises and the U.S. Department of Defense.",
  "icpFit": "weak-fit",
  "icpNotes": "Not a buyer of climate software/data — Scale AI sells AI training data and evaluation services and has no material climate/sustainability program surfaced in public sources. In an AI-data/AI-services framing Scale is a competitor or possible vendor, not a customer. Its only relevance to the Climate Week pipeline is thematic overlap with the 'AI + data centers' track. Recommend deprioritizing as a sales target; classify as weak-fit/competitor-adjacent.",
  "climateWeekRole": "LIKELY FALSE POSITIVE — no verified involvement. task2-description-mining.json lists 'Scale AI' with 2 mentions: 'The Collision – AI's Sustainability Challenge: A Case Study on Data Centers, Emissions…' (2026-09-22) and 'Physical & Digital Decarbonization: Scaling Responsibility Across Corporate Footprints' (2026-09-23). Reading both event descriptions shows the matched string is the lowercase phrase 'scale AI' / 'scaling… AI' (e.g., 'how do we scale AI responsibly', 'Responsible AI at Scale'), and no Scale AI representative or organization is listed among the speakers/panelists (panelists include AWS, Okta, Salesforce, SL Green, Amazon Web Services). Scale AI is absent from sponsors, speakers and event-host lists. Recommend the parent treat both hits as text false positives.",
  "sources": [
   {
    "title": "Scale AI — Scale AI Announces Next Phase of Company's Evolution (Meta investment; >$29B valuation; CEO departure)",
    "url": "https://scale.com/blog/scale-ai-announces-next-phase-of-company-evolution"
   },
   {
    "title": "The New York Times — Meta Invests $14.3 Billion in Scale AI",
    "url": "https://www.nytimes.com/2025/06/12/technology/meta-scale-ai.html"
   },
   {
    "title": "Scale AI — Scale's Series F: $1B at $13.8B valuation (May 2024)",
    "url": "https://scale.com/blog/scale-ai-series-f"
   },
   {
    "title": "TechCrunch — Data-labeling startup Scale AI raises $1B as valuation doubles to $13.8B",
    "url": "https://techcrunch.com/2024/05/21/data-labeling-startup-scale-ai-raises-1b-as-valuation-doubles-to-13-8b/"
   },
   {
    "title": "Business Insider — Scale AI laid off 14% of its 1,400-person workforce (July 2025)",
    "url": "https://www.businessinsider.com/scale-ai-layoffs-hit-genai-team-after-meta-deal-2025-7"
   },
   {
    "title": "JobsByCulture — How Many Employees Does Scale AI Have in 2026? (~1,200 full-time)",
    "url": "https://jobsbyculture.com/blog/scale-ai-employee-count-2026"
   },
   {
    "title": "Revelio Labs — Scale AI employees (total workforce incl. contractors, Mar 2026)",
    "url": "https://www.reveliolabs.com/companies/scale-ai/employees"
   },
   {
    "title": "Climate Week NYC event used as mining evidence: 'The Collision' (string match only)",
    "url": "https://www.climateweeknyc.org/event-search/the-collision-ais-sustainability-challenge-a-case-study-on-data-centers-emissions-and-the-future-of-climate-accountability?hsLang=en"
   }
  ]
 },
 {
  "lane": "C",
  "name": "CoreWeave, Inc.",
  "category": "AI infrastructure / GPU cloud ('AI hyperscaler') — AI + data centers",
  "website": "https://www.coreweave.com",
  "hq": "Livingston, New Jersey, United States",
  "founded": "2017 (as Atlantic Crypto; founders Michael Intrator, Brian Venturo, Brannin McBee, Peter Salanki)",
  "stage": "Public — Nasdaq: CRWV (IPO priced 27 Mar 2025 at $40/share, ~$1.5B raised)",
  "fundingSummary": "Pre-IPO: ~$12.5B raised across debt and equity (CB Insights, including $7.5B+ debt facilities and $1.1B Series C led by Coatue at a $19B valuation in 2024). IPO March 2025 raised ~$1.5B (largest U.S. tech IPO since 2021); Nvidia, Microsoft and OpenAI are key partners/customers. Market cap has traded in the ~$40-50B range in 2026.",
  "headcount": "2189",
  "headcountSource": "CoreWeave FY2025 Form 10-K reports 2,189 employees as of December 31, 2025 (up 148% YoY from 881 in 2024), as compiled by StockAnalysis: https://stockanalysis.com/stocks/crwv/employees/ and Macrotrends: https://www.macrotrends.net/stocks/charts/CRWV/coreweave/number-of-employees. Primary filing: https://www.sec.gov/Archives/edgar/data/1769628/000176962826000104/crwv-20251231.htm",
  "products": "CoreWeave Cloud platform: NVIDIA GPU compute at scale, CPU compute, Kubernetes-native orchestration (CKS), high-performance storage, networking, managed Slurm and inference/agent tooling for AI training and inference; owns/operates purpose-built AI data centers, increasingly powered by contracted renewable/clean power. Customers include leading AI labs, cloud and enterprise buyers (e.g., Microsoft, OpenAI, Nvidia ecosystem).",
  "icpFit": "strong-buyer",
  "icpNotes": "CoreWeave is a large and rapidly growing energy consumer whose core business risk is power availability, grid interconnection, and data-center carbon/water/emissions accounting — evidenced by the existence of a VP, Energy and Sustainability role (Heather McGeory) and by its public presence on AI-power panels. That makes CoreWeave a strong buyer of energy-market data, grid/interconnection analytics, PPA/renewable procurement tooling, carbon accounting, and data-center sustainability reporting software — exactly the ICP for a B2B climate software/data/AI seller.",
  "climateWeekRole": "SPEAKER ORG (no sponsor tier, no hosted events). cw-speakers-raw.json lists Heather McGeory, Vice President, Energy and Sustainability, CoreWeave among the 70 official Climate Week NYC 2026 speakers; candidate universe shows CoreWeave with sources ['speakers'], roles ['speaker-org'], events_hosted 0. CoreWeave has no sponsor/partner tier, no event-host records, and 0 description-mining mentions. The speaker appears in the AI-and-power thematic track (e.g., 'AI needs power' / data-center-narrative events where Sunrun also appears).",
  "sources": [
   {
    "title": "CoreWeave — Announces Pricing of Initial Public Offering (27 Mar 2025)",
    "url": "https://investors.coreweave.com/news/news-details/2025/CoreWeave-Announces-Pricing-of-Initial-Public-Offering/default.aspx"
   },
   {
    "title": "CNBC — CoreWeave opens at $39 after biggest U.S. tech IPO since 2021 ($1.5B raised)",
    "url": "https://www.cnbc.com/2025/03/28/coreweave-starts-trading-on-nasdaq-at-per-share.html"
   },
   {
    "title": "CoreWeave, Inc. — Form 10-K for FY2025 (SEC)",
    "url": "https://www.sec.gov/Archives/edgar/data/1769628/000176962826000104/crwv-20251231.htm"
   },
   {
    "title": "StockAnalysis — CoreWeave number of employees (2,189 as of Dec 31, 2025)",
    "url": "https://stockanalysis.com/stocks/crwv/employees/"
   },
   {
    "title": "Macrotrends — CoreWeave employee count 2024-2025",
    "url": "https://www.macrotrends.net/stocks/charts/CRWV/coreweave/number-of-employees"
   },
   {
    "title": "Wikipedia — CoreWeave (founded 2017; HQ Livingston, NJ; Nasdaq: CRWV)",
    "url": "https://en.wikipedia.org/wiki/CoreWeave"
   },
   {
    "title": "CB Insights — CoreWeave profile (founded 2017; total raised ~$12.5B)",
    "url": "https://www.cbinsights.com/company/coreweave"
   },
   {
    "title": "CoreWeave — About us",
    "url": "https://www.coreweave.com/about-us"
   }
  ]
 },
 {
  "lane": "C",
  "name": "Ambrook",
  "category": "Agricultural finance / fintech SaaS (farm accounting and financial management)",
  "website": "https://ambrook.com",
  "hq": "New York, NY, United States",
  "founded": "2020 (co-founders Mackenzie Burnett, Dan Schlosser, Jeff Anders; press describes it as a 'six-year-old fintech' as of Aug 2026)",
  "stage": "Private, VC-backed — Series B (Aug 2026)",
  "fundingSummary": "$26.1M Series A led by Thrive Capital and Dylan Field (Field Ventures), with Homebrew, BoxGroup, Designer Fund, Mischief, Not Boring (Jul 2025) — described by the company as $29M total raised at that point; plus a $30M Series B led by Lachy Groom with Thomson Reuters Ventures, Thrive Capital, Field Ventures and Cameron Ventures (Aug 2026). Approx. $59M disclosed total.",
  "headcount": "53",
  "headcountSource": "PitchBook company profile for Ambrook lists 'Employees 53' (profile accessed 2026): https://pitchbook.com/profiles/company/465227-29. This is a directory approximation that may lag the Aug 2026 Series B hiring; no company-reported headcount was found, so treat 53 as the last verifiable approximation rather than a current figure.",
  "products": "Financial management platform built for farmers, ranchers and other independent 'real economy' businesses: bookkeeping, invoicing, expense tracking, cash-flow management, bill pay, and funding/tax advisory; sold as a QuickBooks alternative with industry-specific workflows (e.g., commodity, livestock, land). Grew from ~2,500 to 8,000+ businesses in a year and is expanding beyond agriculture into trucking, contracting and real estate (Aug 2026).",
  "icpFit": "partner (weak buyer fit)",
  "icpNotes": "Ambrook sells software to farmers/ranchers; it is a small company (~50-100 people) with limited budget for third-party climate software and no clear climate/sustainability data mandate, so direct buyer fit is weak. Its relevance is as an ecosystem/community partner: it sits at the center of the American farm and food-production audience, and its 2 Climate Week NYC events show it invests in brand/community in exactly this buyer landscape. Possible future buyer of ag carbon/soil or agronomy data if it extends into sustainability-linked finance — track, don't prioritize as a buyer.",
  "climateWeekRole": "EVENT HOST — 2 confirmed Climate Week NYC 2026 events, both community/brand-build events rather than climate-software programming: 'Sweater Party' (2026-09-22), where Ambrook is soft-launching 'Big Dipper Wool', a pilot batch of sweaters sourced from an upstate-NY flock via Green Mountain Spinnery; and 'Corn Party' (2026-09-23), co-hosted with Offrange, celebrating corn in American farming. task2-description-mining.json records 'Ambrook' with 2 mentions (event slugs sweater-party, corn-party); the candidate universe lists Ambrook as an event-host (events_hosted 1 in that artifact — the two-slug mining list is the more complete evidence). No sponsor tier, no speaker-record entry.",
  "sources": [
   {
    "title": "Fortune — Ambrook raises $26.1 million Series A to provide farmers and ranchers with better accounting software",
    "url": "https://fortune.com/2025/07/01/exclusive-ambrook-raises-26-1-million-series-a-to-provide-farmers-and-ranchers-with-better-accounting-software/"
   },
   {
    "title": "Ambrook — America, the Beautiful ($29M total raised; Series A led by Thrive Capital)",
    "url": "https://ambrook.com/blog/announcements/america-the-beautiful"
   },
   {
    "title": "Ambrook — We raised our $30M Series B, led by Lachy Groom (Aug 2026)",
    "url": "https://ambrook.com/series-b"
   },
   {
    "title": "Agriculture of America — Ambrook Raises $30M, Grows to 8,000+ Customers",
    "url": "https://www.agricultureofamerica.com/2026/08/06/ambrook-raises-30m-grows-to-8000-customers/"
   },
   {
    "title": "Upstarts Media — Ambrook, A QuickBooks Killer For Farms, Raises $30M",
    "url": "https://www.upstartsmedia.com/p/ambrook-raises-30m-series-b-real-economy"
   },
   {
    "title": "PitchBook — Ambrook profile (founded 2020; employees 53)",
    "url": "https://pitchbook.com/profiles/company/465227-29"
   },
   {
    "title": "CB Insights — Ambrook profile (founded 2020; Series A; total raised $26.1M)",
    "url": "https://www.cbinsights.com/company/ambrook"
   },
   {
    "title": "Climate Week NYC event evidence: 'Sweater Party' (Ambrook launch)",
    "url": "https://www.climateweeknyc.org/event-search/sweater-party?hsLang=en"
   },
   {
    "title": "Climate Week NYC event evidence: 'Corn Party' (Ambrook + Offrange)",
    "url": "https://www.climateweeknyc.org/event-search/corn-party?hsLang=en"
   }
  ]
 },
 {
  "lane": "C",
  "name": "Sunrun Inc.",
  "category": "Residential solar + battery storage (public company); #1 U.S. home solar and storage provider",
  "website": "https://www.sunrun.com",
  "hq": "San Francisco, California, United States",
  "founded": "2007; IPO August 2015",
  "stage": "Public — Nasdaq: RUN",
  "fundingSummary": "Public company; raised capital via IPO (Aug 2015) and subsequent debt/equity and project-financing (securitizations, tax-equity and financing funds). Not VC-funded. FY2025 revenue ~$3.5B, net income ~$400M; market cap ~$2.4B in Aug 2026. Headcount was reduced ~18% YoY in 2025 as the company cut costs.",
  "headcount": "9059",
  "headcountSource": "Sunrun FY2025 Form 10-K reports 9,059 employees as of December 31, 2025 (down 1,999 / -18.1% YoY), compiled by StockAnalysis: https://stockanalysis.com/stocks/run/employees/. Primary filing: https://investors.sunrun.com/filings-financials/sec-filings/content/0001628280-26-012289/run-20251231.htm (filed 2026-02-26).",
  "products": "Residential solar + battery storage systems sold via lease/PPA/subscription and cash purchase; installation and service; home-to-grid 'power plants' / virtual power plant (VPP) and demand-response offerings that dispatch customer batteries to the grid; energy services to utilities and grid operators. Sunrun is also a major player in the residential solar financing/tax-equity market (relevant overlap with Crux's tax-credit ecosystem).",
  "icpFit": "buyer",
  "icpNotes": "Sunrun is a large enterprise with real, recurring needs for corporate sustainability reporting (it publishes sustainability disclosures), grid/market data, VPP and demand-response analytics, customer energy data, and finance/tax-credit tooling. It is a credible buyer of energy data, market analytics, carbon/reporting software and AI-driven energy optimisation — though it also builds significant software in-house. Strong, well-resourced prospect with high Climate Week engagement; classify as buyer (not strong-buyer because of in-house build and cost discipline/headcount cuts).",
  "climateWeekRole": "HIGH — presenting sponsor of a flagship day of programming plus CEO speaking role; not an official Climate Group sponsor/partner. task2-description-mining.json records 'Sunrun' with 8 mentions across events, all clustered in 'Antenna House: The Value Transition, Presented by Sunrun, Powered by Antenna Group' (2026-09-23, full-day at LUME Studios, 393 Broadway) and its sub-sessions ('The Customer-First Path to Powering AI', 'AI Needs More Power…', 'Shaping the Data Center Narrative', 'Trophy Assets Don't Need Saving…', 'The State of Climate Storytelling', 'Where Sustainability Meets Storytelling'), plus 'The Race to Build the Next Generation City' (Voltera CEO session, same Antenna House venue). Sunrun CEO Mary Powell speaks in a fireside with Fortune's Diane Brady. Sunrun is absent from cw-sponsors-partners-raw.json (the presenting-sponsor role is at event level, via Antenna Group) and from cw-speakers-raw.json.",
  "sources": [
   {
    "title": "Sunrun — FY2025 Form 10-K (employees 9,059 as of Dec 31, 2025)",
    "url": "https://investors.sunrun.com/filings-financials/sec-filings/content/0001628280-26-012289/run-20251231.htm"
   },
   {
    "title": "StockAnalysis — Sunrun number of employees (9,059; -18.1% YoY)",
    "url": "https://stockanalysis.com/stocks/run/employees/"
   },
   {
    "title": "Sunrun — Investor Relations (Nasdaq: RUN; America's largest residential battery storage + solar provider)",
    "url": "https://investors.sunrun.com/"
   },
   {
    "title": "Wikipedia — Sunrun (founded 2007; HQ San Francisco; IPO Aug 2015)",
    "url": "https://en.wikipedia.org/wiki/Sunrun"
   },
   {
    "title": "Sunrun — corporate site",
    "url": "https://www.sunrun.com/"
   },
   {
    "title": "Climate Week NYC event evidence: 'Antenna House: The Value Transition, Presented by Sunrun'",
    "url": "https://www.climateweeknyc.org/event-search/antenna-house-the-value-transition-presented-by-sunrun-powered-by-antenna-group?hsLang=en"
   }
  ]
 },
 {
  "lane": "C",
  "name": "Voltera (Voltera Power / EvConneX, LLC)",
  "category": "EV charging & fleet energy infrastructure developer/operator (EV charging hubs for fleets and autonomous ride-hail) — private-equity backed",
  "website": "https://www.volterapower.com",
  "hq": "Culver City, California, United States (site footer address); EQT portfolio page lists Los Angeles, CA",
  "founded": "2022 (official launch with EQT support; signed first customer in 2021)",
  "stage": "Private — PE-backed by EQT Infrastructure (EQT entry 2022); in May 2026 Voltera and Revel announced a combination to form a scaled EV/autonomous fleet infrastructure platform",
  "fundingSummary": "Not VC-funded in the conventional sense: recapitalized and owned by EQT Infrastructure (EQT entered 2022), which funds hub development. Third-party directories cite ~$100M funding. In May 2026 Voltera and Revel announced a definitive agreement to combine, creating 'North America's leading autonomous infrastructure provider' (deal terms undisclosed in public sources); Revel CEO Frank Reig leads the combined company as Voltera CEO. Reported network: ~500 charging stalls live/substantially advanced at the time of the BloombergNEF interview.",
  "headcount": "44",
  "headcountSource": "LinkedIn company page for Voltera (volterapower) reports ~44 employees (profile snapshot indexed Jun 2026): https://linkedin.com/company/volterapower. Directory estimates vary (AeroLeads lists 53). No company-reported headcount found; treat 44 as a LinkedIn approximation that may understate the post-Revel-combination organization.",
  "products": "Purpose-built high-uptime EV fleet charging hubs and energy infrastructure: site development, utility interconnection, design-build and operation of charging depots for ride-hail, delivery and autonomous vehicle fleets (customers have included autonomous ride-hail operators); related energy services (demand management, resiliency, on-site power) and data/uptime management across hubs in major North American metros. Now explicitly positioned as 'infrastructure behind autonomous mobility'.",
  "icpFit": "buyer",
  "icpNotes": "Voltera's business is fundamentally an energy-infrastructure problem: site selection, utility/grid interconnection, power procurement, demand charges/load management, and uptime/energy analytics for charging hubs. That makes Voltera a solid buyer of energy-market and grid data, charging-network analytics, and sustainability/scope-2 reporting tooling — the exact ICP for a B2B climate software/data/AI seller. Sized ~44-100 people under PE ownership (EQT), so deal sizes are mid-market; classify as buyer (not strong-buyer due to size), with the Voltera+Revel combination likely expanding the energy-data budget.",
  "climateWeekRole": "OFFICIAL SPONSOR + SPEAKER. Voltera is listed in cw-sponsors-partners-raw.json at tier 'Thematic Session Partner' (detail_url climateweeknyc.org/sponsors-and-partners/voltera). Candidate-universe entry: sources ['sponsors-and-partners','speakers'], roles ['sponsor:Thematic Session Partner','speaker-org']. Voltera CEO Frank Reig is listed in cw-speakers-raw.json (name 'Frank Reig', title 'CEO', org 'Voltera'). Voltera is featured in the event 'The Race to Build the Next Generation City: A Conversation with Voltera CEO Frank Reig' (2026-09-23), and also appears via description mining (1 mention) in the Antenna House / Sunrun day. This is the strongest, most unambiguous Climate Week commitment among the 8 companies.",
  "sources": [
   {
    "title": "Voltera — About (founded 2022; Culver City, CA address; Voltera+Revel combination 2026; CEO Frank Reig)",
    "url": "https://www.volterapower.com/about"
   },
   {
    "title": "EQT Group — Voltera current portfolio (Established 2022; HQ Los Angeles; entry 2022)",
    "url": "https://eqtgroup.com/about/current-portfolio/voltera"
   },
   {
    "title": "Voltera — Voltera and Revel Announce Combination to Create Scaled EV Infrastructure Platform (May 2026)",
    "url": "https://www.volterapower.com/post/voltera-and-revel-announce-combination-to-create-scaled-ev-infrastructure-platform-for-fleet-and-autonomous-mobility"
   },
   {
    "title": "LinkedIn — Voltera company page (~44 employees, Jun 2026)",
    "url": "https://linkedin.com/company/volterapower"
   },
   {
    "title": "AeroLeads — Voltera company details (53 employees; founded 2022; funding $100M)",
    "url": "https://aeroleads.com/c/volterapower"
   },
   {
    "title": "Climate Week NYC event evidence: 'The Race to Build the Next Generation City: A Conversation with Voltera CEO Frank Reig'",
    "url": "https://www.climateweeknyc.org/event-search/the-race-to-build-the-next-generation-city-a-conversation-with-voltera-ceo-frank-reig?hsLang=en"
   },
   {
    "title": "Climate Week NYC sponsor listing evidence: Voltera — Thematic Session Partner (cw-sponsors-partners-raw.json)",
    "url": "https://www.climateweeknyc.org/sponsors-and-partners/voltera"
   }
  ]
 },
 {
  "lane": "C",
  "name": "Google (Alphabet Inc.) — with Microsoft (Microsoft Corporation) noted in the same entry",
  "category": "Hyperscale cloud + AI (both a potential channel partner and a direct competitor in climate/sustainability software)",
  "website": "https://abc.xyz / https://cloud.google.com (Google Cloud sustainability) ; Microsoft: https://www.microsoft.com / https://www.microsoft.com/en-us/sustainability",
  "hq": "Google / Alphabet: Mountain View, California, USA. Microsoft: Redmond, Washington, USA.",
  "founded": "Google 1998 (Alphabet Inc. holding company created 2015); Microsoft 1975",
  "stage": "Public — Google/Alphabet: Nasdaq: GOOGL / GOOG; Microsoft: Nasdaq: MSFT",
  "fundingSummary": "Both are mega-cap public companies (no venture funding relevant). Alphabet FY2025 revenue $402B+ run-rate ($113.8B in Q4 2025 alone, +18% YoY) with Google Cloud accelerating; Microsoft FY2025 revenue ~$281.7B (FY2026 ~$331.8B per the FY2026 filing) — capital markets, not VC, funds both. Alphabet continues large debt/equity issuance to fund AI/data-center capex.",
  "headcount": "190820",
  "headcountSource": "Alphabet: 190,820 employees for fiscal year 2025 (Tickerleague compilation of the Alphabet FY2025 10-K, +4.1% YoY): https://tickerleague.com/companies/GOOGL/employee-count; corroborated by Statista: https://www.statista.com/statistics/273744/number-of-full-time-google-employees/ and the primary filing https://www.sec.gov/Archives/edgar/data/1652044/000165204426000018/goog-20251231.htm. Microsoft: ~228,000 employees for FY2025 (TradingEconomics compilation of Microsoft's 10-K): https://tradingeconomics.com/msft:us:employees; Statista: https://www.statista.com/statistics/273475/number-of-employees-at-the-microsoft-corporation-since-2005/; primary filing https://www.sec.gov/Archives/edgar/data/789019/000095017025100235/msft-20250630.htm",
  "products": "Google/Alphabet: search and advertising, YouTube, Android, Google Cloud (GCP), Google Workspace, Gemini AI models, and a sustainability product set that includes Google Cloud Carbon Footprint, carbon-intelligent computing, Google Earth Engine (geospatial/climate data), and sustainability reporting/data-transfer tooling for CSRD and similar frameworks. Microsoft: Azure cloud, Microsoft 365, Copilot/AI, and a dedicated sustainability software line — Microsoft Cloud for Sustainability / Microsoft Sustainability Manager (carbon accounting, ESG reporting, emissions data) plus the Planetary Computer (environmental data platform) and carbon-negative/water-positive corporate commitments. Both also operate huge data-center fleets with aggressive clean-energy procurement, making them major corporate buyers of clean power and energy data even as they sell competing software.",
  "icpFit": "competitor (secondary channel-partner opportunity)",
  "icpNotes": "Google and Microsoft are primarily COMPETITORS for a B2B climate software/data/AI seller: Google Cloud sells Carbon Footprint and Earth Engine; Microsoft sells Sustainability Manager / Cloud for Sustainability. They also own the cloud marketplaces through which a smaller climate software vendor might distribute, and they buy enormous quantities of clean energy and energy/grid data for their own data-center fleets — so there is a real (if hard-to-win) enterprise-buyer motion for specialized energy/grid data they don't build in-house. Net classification for a climate-software seller: competitor first, with a possible partner/marketplace motion; do not treat as a classic buyer.",
  "climateWeekRole": "GOOGLE: minimal and largely incidental — no sponsor tier, no speaker record, no hosted events. task2-description-mining.json records 5 'Google' mentions, but on inspection they are generic strings, not participation: 'Google Android App Store' (restaurant POS event), a Google Form registration link ('The Energy Smörgåsbord'), a book-retail listing ('Google Books' in the Bold Women event), and a protest action outside 'Google's Chelsea offices' ('AI Fans the Climate Crisis', 2026-09-23 — an advocacy event demanding a moratorium on hyperscale data centers). Only the last is a genuine Google reference and it is adversarial. MICROSOFT: real but partner-level involvement — 3 verified mentions: (1) partner on 'Voice of the Future: Building Inclusive AI for African National Languages' (2026-09-22, hosted by Congo Youth Coalition at 48 Wall Street, 'in partnership with Microsoft'); (2) Noelle Walsh, President, Cloud Operations and Innovation, Microsoft, listed among speakers at 'Pillars of Stability: Building Resilient Systems' (2026-09-22); (3) 'TRACE THE UNSEEN: Climate Intelligence Build Day' (2026-09-25) hosted at the Microsoft Garage in SoHo. Neither company appears in the 39-name sponsor/partner list.",
  "sources": [
   {
    "title": "Alphabet Inc. — Form 10-K for FY2025 (SEC)",
    "url": "https://www.sec.gov/Archives/edgar/data/1652044/000165204426000018/goog-20251231.htm"
   },
   {
    "title": "Tickerleague — Alphabet (GOOGL) employee count (190,820, FY2025)",
    "url": "https://tickerleague.com/companies/GOOGL/employee-count"
   },
   {
    "title": "Statista — Alphabet: number of full-time employees 2007-2025",
    "url": "https://www.statista.com/statistics/273744/number-of-full-time-google-employees/"
   },
   {
    "title": "Alphabet — Q4 and Fiscal Year 2025 Results",
    "url": "https://s206.q4cdn.com/479360582/files/doc_financials/2025/q4/2025q4-alphabet-earnings-release.pdf"
   },
   {
    "title": "Microsoft Corporation — Form 10-K for FY2025 (SEC)",
    "url": "https://www.sec.gov/Archives/edgar/data/789019/000095017025100235/msft-20250630.htm"
   },
   {
    "title": "TradingEconomics — Microsoft employees (228K, FY2025)",
    "url": "https://tradingeconomics.com/msft:us:employees"
   },
   {
    "title": "Statista — Microsoft Corporation number of employees 2005-2026",
    "url": "https://www.statista.com/statistics/273475/number-of-employees-at-the-microsoft-corporation-since-2005/"
   },
   {
    "title": "Microsoft — 2025 Annual Report",
    "url": "https://www.microsoft.com/investor/reports/ar25/"
   },
   {
    "title": "Climate Week NYC event evidence: 'AI Fans the Climate Crisis' (protest outside Google's Chelsea offices)",
    "url": "https://www.climateweeknyc.org/event-search/ai-fans-the-climate-crisis?hsLang=en"
   },
   {
    "title": "Climate Week NYC event evidence: 'Pillars of Stability' (Noelle Walsh, Microsoft, speaker)",
    "url": "https://www.climateweeknyc.org/event-search/pillars-of-stability-building-resilient-systems?hsLang=en"
   },
   {
    "title": "Climate Week NYC event evidence: 'TRACE THE UNSEEN' (at Microsoft Garage, SoHo)",
    "url": "https://www.climateweeknyc.org/event-search/trace-the-unseen-climate-intelligence-build-day?hsLang=en"
   }
  ]
 }
];
